part of 'video_kind_classifier.dart';

final class _VideoKindKeywordRule {
  const _VideoKindKeywordRule({
    required this.kind,
    required this.baseConfidence,
    required this.keywords,
  });

  final String kind;
  final double baseConfidence;
  final List<String> keywords;
}

const List<_VideoKindKeywordRule> _filenameKindRules = <_VideoKindKeywordRule>[
  _VideoKindKeywordRule(
    kind: kVideoKindScreenRecording,
    baseConfidence: 0.94,
    keywords: <String>[
      'screen recording',
      'screen_recording',
      'screenrecording',
      'screen capture',
      'screen_capture',
      'screenshare',
      'screen share',
      'screencast',
      '录屏',
      '屏幕录制',
      '荧幕录制',
      '画面録画',
      '画面収録',
      '스크린 녹화',
      '화면 녹화',
      'grabacion de pantalla',
      'grabación de pantalla',
      'enregistrement d ecran',
      "enregistrement d'écran",
      'bildschirmaufnahme',
      'gravacao de tela',
      'gravação de tela',
      'registrazione schermo',
      'запись экрана',
      'تسجيل الشاشة',
      'स्क्रीन रिकॉर्डिंग',
    ],
  ),
  _VideoKindKeywordRule(
    kind: kVideoKindGameplay,
    baseConfidence: 0.9,
    keywords: <String>[
      'gameplay',
      'playthrough',
      'speedrun',
      'bossfight',
      'boss fight',
      'ranked',
      'esports',
      'stream highlight',
      '游戏',
      '实况',
      '对局',
      'ゲームプレイ',
      'ゲーム実況',
      '게임플레이',
      '게임 방송',
      'juego',
      'partida',
      'partie',
      'spiel',
      'jogo',
      'gioco',
      'игра',
      'геймплей',
      'لعبة',
      'गेमप्ले',
    ],
  ),
  _VideoKindKeywordRule(
    kind: kVideoKindInterview,
    baseConfidence: 0.88,
    keywords: <String>[
      'interview',
      'mock interview',
      'candidate interview',
      'podcast',
      'qa session',
      'q and a',
      'q&a',
      '访谈',
      '面试',
      '对谈',
      'インタビュー',
      '인터뷰',
      'entrevista',
      'entretien',
      'vorstellungsgesprach',
      'vorstellungsgespräch',
      'bewerbungsgesprach',
      'bewerbungsgespräch',
      'colloquio',
      'intervista',
      'интервью',
      'собеседование',
      'مقابلة',
      'سؤال وجواب',
      'साक्षात्कार',
    ],
  ),
  _VideoKindKeywordRule(
    kind: kVideoKindMeeting,
    baseConfidence: 0.86,
    keywords: <String>[
      'meeting',
      'standup',
      'daily sync',
      'retro',
      'retrospective',
      'all hands',
      'zoom',
      'teams meeting',
      '会议',
      '会議',
      'ミーティング',
      '회의',
      'reunion',
      'reunión',
      'réunion',
      'besprechung',
      'sitzung',
      'reuniao',
      'reunião',
      'riunione',
      'встреча',
      'совещание',
      'اجتماع',
      'बैठक',
    ],
  ),
  _VideoKindKeywordRule(
    kind: kVideoKindTutorial,
    baseConfidence: 0.84,
    keywords: <String>[
      'tutorial',
      'how to',
      'walkthrough',
      'guide',
      'setup guide',
      'install guide',
      '教程',
      '教学',
      '指南',
      'チュートリアル',
      '튜토리얼',
      'guia',
      'guía',
      'tutoriel',
      'anleitung',
      'passo a passo',
      'guida',
      'руководство',
      'учебник',
      'دليل',
      'ट्यूटोरियल',
      'मार्गदर्शिका',
    ],
  ),
  _VideoKindKeywordRule(
    kind: kVideoKindLecture,
    baseConfidence: 0.82,
    keywords: <String>[
      'lecture',
      'lesson',
      'course',
      'classroom',
      'seminar',
      '讲座',
      '课程',
      '课堂',
      '講義',
      '강의',
      'leccion',
      'lección',
      'cours',
      'vorlesung',
      'unterricht',
      'aula',
      'lezione',
      'лекция',
      'محاضرة',
      'व्याख्यान',
    ],
  ),
  _VideoKindKeywordRule(
    kind: kVideoKindPresentation,
    baseConfidence: 0.8,
    keywords: <String>[
      'presentation',
      'keynote',
      'pitch deck',
      'slides',
      'deck',
      'roadshow',
      'demo day',
      '发布会',
      '演示',
      '汇报',
      'プレゼン',
      '발표',
      'presentacion',
      'presentación',
      'présentation',
      'praesentation',
      'präsentation',
      'vortrag',
      'apresentacao',
      'apresentação',
      'presentazione',
      'презентация',
      'عرض تقديمي',
      'प्रस्तुति',
    ],
  ),
  _VideoKindKeywordRule(
    kind: kVideoKindVlog,
    baseConfidence: 0.76,
    keywords: <String>[
      'vlog',
      'daily vlog',
      'travel vlog',
      'day in my life',
      '日常',
      '生活记录',
      '随拍',
      '日常記録',
      '브이로그',
      '일상',
      'diario',
      'journal',
      'tagebuch',
      'cotidiano',
      'giornata',
      'дневник',
      'يوميات',
      'दैनिक',
    ],
  ),
];

const List<_VideoKindKeywordRule> _ocrKindRules = <_VideoKindKeywordRule>[
  _VideoKindKeywordRule(
    kind: kVideoKindGameplay,
    baseConfidence: 0.72,
    keywords: <String>[
      'level',
      'quest',
      'boss',
      'damage',
      'kill',
      'score',
      'fps',
      'inventory',
      'minimap',
      'xp',
      '击杀',
      '关卡',
      '战绩',
      'ステージ',
      '킬',
      'nivel',
      'niveau',
      'stufe',
      'puntaje',
      'punkte',
      'placar',
      'punteggio',
      'урон',
      'очки',
      'ضرر',
      'स्कोर',
    ],
  ),
  _VideoKindKeywordRule(
    kind: kVideoKindInterview,
    baseConfidence: 0.7,
    keywords: <String>[
      'interviewer',
      'candidate',
      'question',
      'answer',
      'host',
      'guest',
      'interview',
      '面试官',
      '候选人',
      '问题',
      '回答',
      '質問',
      '답변',
      'entrevista',
      'entretien',
      'vorstellungsgespräch',
      'frage',
      'antwort',
      'pregunta',
      'respuesta',
      'colloquio',
      'domanda',
      'risposta',
      'интервью',
      'вопрос',
      'ответ',
      'مقابلة',
      'سؤال',
      'جواب',
      'साक्षात्कार',
      'प्रश्न',
      'उत्तर',
    ],
  ),
  _VideoKindKeywordRule(
    kind: kVideoKindMeeting,
    baseConfidence: 0.7,
    keywords: <String>[
      'agenda',
      'action items',
      'next steps',
      'blockers',
      'standup',
      'retrospective',
      'meeting notes',
      'attendees',
      'owner',
      'due date',
      '会议纪要',
      '待办',
      '会議メモ',
      '회의록',
      'reunion',
      'réunion',
      'besprechung',
      'acciones',
      'prochaines étapes',
      'nächste schritte',
      'reunião',
      'azioni',
      'riunione',
      'встреча',
      'повестка',
      'اجتماع',
      'جدول الأعمال',
      'बैठक',
      'कार्यसूची',
    ],
  ),
  _VideoKindKeywordRule(
    kind: kVideoKindTutorial,
    baseConfidence: 0.7,
    keywords: <String>[
      'tutorial',
      'step',
      'how to',
      'install',
      'setup',
      'configure',
      'prerequisite',
      'example',
      '教程',
      '步骤',
      '安装',
      '配置',
      '手順',
      '설정',
      'paso',
      'étape',
      'schritt',
      'instalar',
      'installer',
      'installieren',
      'passo',
      'guida',
      'руководство',
      'учебник',
      'دليل',
      'تعليمات',
      'ट्यूटोरियल',
      'कदम',
    ],
  ),
  _VideoKindKeywordRule(
    kind: kVideoKindLecture,
    baseConfidence: 0.7,
    keywords: <String>[
      'lecture',
      'chapter',
      'syllabus',
      'professor',
      'semester',
      'homework',
      'assignment',
      '课后',
      '讲义',
      '章节',
      '講義',
      '課題',
      '강의',
      'lección',
      'cours',
      'vorlesung',
      'aufgabe',
      'hausaufgabe',
      'aula',
      'lezione',
      'лекция',
      'домашнее задание',
      'محاضرة',
      'واجب',
      'व्याख्यान',
      'होमवर्क',
    ],
  ),
  _VideoKindKeywordRule(
    kind: kVideoKindPresentation,
    baseConfidence: 0.7,
    keywords: <String>[
      'slide',
      'roadmap',
      'kpi',
      'revenue',
      'market',
      'summary',
      'conclusion',
      'thank you',
      'overview',
      '目标',
      '结论',
      '汇报',
      'プレゼン',
      '발표',
      'resumen',
      'résumé',
      'zusammenfassung',
      'umsatz',
      'apresentação',
      'presentazione',
      'презентация',
      'итоги',
      'عرض تقديمي',
      'ملخص',
      'प्रस्तुति',
      'सारांश',
    ],
  ),
  _VideoKindKeywordRule(
    kind: kVideoKindScreenRecording,
    baseConfidence: 0.68,
    keywords: <String>[
      'terminal',
      'browser',
      'tab',
      'window',
      'file explorer',
      'cursor',
      '代码',
      '终端',
      '命令行',
      'ターミナル',
      '브라우저',
      'navegador',
      'navigateur',
      'fenêtre',
      'fenster',
      'navegador',
      'janela',
      'schermo',
      'терминал',
      'браузер',
      'متصفح',
      'نافذة',
      'टर्मिनल',
      'ब्राउज़र',
    ],
  ),
];

const String _kDefaultVideoKindLanguageHints = 'device_plus_en';

const Map<String, List<String>> _kVideoKindHintKeywordByHint =
    <String, List<String>>{
  'zh_en': <String>['中文', '汉字', '繁體', '简体', '教程', '会议'],
  'ja_en': <String>['日本語', 'かな', 'カナ', '会議', '講義', 'プレゼン'],
  'ko_en': <String>['한국어', '회의', '강의', '튜토리얼', '인터뷰'],
  'es_en': <String>[
    'reunion',
    'reunión',
    'equipo',
    'entrevista',
    'tutorial',
    'presentacion',
    'presentación',
    'reuniao',
    'reunião',
    'apresentacao',
    'apresentação',
    'jogo',
    'aula',
  ],
  'fr_en': <String>[
    'réunion',
    'entretien',
    'tutoriel',
    'présentation',
    'équipe',
    'riunione',
    'colloquio',
    'presentazione',
    'lezione',
    'guida',
  ],
  'de_en': <String>[
    'besprechung',
    'vorstellungsgespräch',
    'vorstellungsgesprach',
    'vorlesung',
    'präsentation',
    'praesentation',
    'sitzung',
  ],
};

String _resolveVideoKindOcrLanguageHints(
  String languageHints,
  String filename,
) {
  final normalized = languageHints.trim();
  if (normalized.isNotEmpty &&
      normalized.toLowerCase() != _kDefaultVideoKindLanguageHints) {
    return normalized;
  }

  final inferred = _inferVideoKindLanguageHintsFromFilename(filename);
  return inferred ?? _kDefaultVideoKindLanguageHints;
}

String? _inferVideoKindLanguageHintsFromFilename(String filename) {
  final normalized = filename.trim().toLowerCase();
  if (normalized.isEmpty) return null;

  if (RegExp(r'[\u3040-\u30FF]').hasMatch(normalized)) {
    return 'ja_en';
  }
  if (RegExp(r'[\uAC00-\uD7AF]').hasMatch(normalized)) {
    return 'ko_en';
  }
  if (RegExp(r'[\u4E00-\u9FFF]').hasMatch(normalized)) {
    return 'zh_en';
  }

  final candidate = normalized.replaceAll(RegExp(r'[_\-.]+'), ' ');
  for (final entry in _kVideoKindHintKeywordByHint.entries) {
    for (final keyword in entry.value) {
      if (_containsKeyword(candidate, keyword)) {
        return entry.key;
      }
    }
  }

  return null;
}
