pub mod api;
pub mod auth;
pub mod content_extract;
pub mod crypto;
pub mod db;
pub mod desktop_media;
#[cfg(not(target_family = "wasm"))]
pub mod embedding;
#[cfg(target_family = "wasm")]
#[path = "embedding/wasm.rs"]
pub mod embedding;
mod frb_generated;
#[cfg(not(target_family = "wasm"))]
pub mod geo;
#[cfg(target_family = "wasm")]
#[path = "geo/wasm.rs"]
pub mod geo;
#[cfg(not(target_family = "wasm"))]
pub mod llm;
#[cfg(target_family = "wasm")]
#[path = "llm/wasm.rs"]
pub mod llm;
pub mod local_model_lifecycle;
#[cfg(not(target_family = "wasm"))]
pub mod media_annotation;
#[cfg(target_family = "wasm")]
#[path = "media_annotation/wasm.rs"]
pub mod media_annotation;
pub(crate) mod message_citations;
pub mod platform;
pub mod rag;
pub mod semantic_parse;
pub mod sync;
pub mod url_enrichment_ai;
pub mod vector; /* AUTO INJECTED BY flutter_rust_bridge. This line may not be accurate, and you can change it according to your needs. */
