// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Attachment {
  final String sha256;
  final String mimeType;
  final String path;
  final PlatformInt64 byteLen;
  final PlatformInt64 createdAtMs;

  const Attachment({
    required this.sha256,
    required this.mimeType,
    required this.path,
    required this.byteLen,
    required this.createdAtMs,
  });

  @override
  int get hashCode =>
      sha256.hashCode ^
      mimeType.hashCode ^
      path.hashCode ^
      byteLen.hashCode ^
      createdAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Attachment &&
          runtimeType == other.runtimeType &&
          sha256 == other.sha256 &&
          mimeType == other.mimeType &&
          path == other.path &&
          byteLen == other.byteLen &&
          createdAtMs == other.createdAtMs;
}

class Conversation {
  final String id;
  final String title;
  final PlatformInt64 createdAtMs;
  final PlatformInt64 updatedAtMs;

  const Conversation({
    required this.id,
    required this.title,
    required this.createdAtMs,
    required this.updatedAtMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      createdAtMs.hashCode ^
      updatedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Conversation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          createdAtMs == other.createdAtMs &&
          updatedAtMs == other.updatedAtMs;
}

class Event {
  final String id;
  final String title;
  final PlatformInt64 startAtMs;
  final PlatformInt64 endAtMs;
  final String tz;
  final String? sourceEntryId;
  final PlatformInt64 createdAtMs;
  final PlatformInt64 updatedAtMs;

  const Event({
    required this.id,
    required this.title,
    required this.startAtMs,
    required this.endAtMs,
    required this.tz,
    this.sourceEntryId,
    required this.createdAtMs,
    required this.updatedAtMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      startAtMs.hashCode ^
      endAtMs.hashCode ^
      tz.hashCode ^
      sourceEntryId.hashCode ^
      createdAtMs.hashCode ^
      updatedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Event &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          startAtMs == other.startAtMs &&
          endAtMs == other.endAtMs &&
          tz == other.tz &&
          sourceEntryId == other.sourceEntryId &&
          createdAtMs == other.createdAtMs &&
          updatedAtMs == other.updatedAtMs;
}

class LlmProfile {
  final String id;
  final String name;
  final String providerType;
  final String? baseUrl;
  final String modelName;
  final bool isActive;
  final PlatformInt64 createdAtMs;
  final PlatformInt64 updatedAtMs;

  const LlmProfile({
    required this.id,
    required this.name,
    required this.providerType,
    this.baseUrl,
    required this.modelName,
    required this.isActive,
    required this.createdAtMs,
    required this.updatedAtMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      providerType.hashCode ^
      baseUrl.hashCode ^
      modelName.hashCode ^
      isActive.hashCode ^
      createdAtMs.hashCode ^
      updatedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LlmProfile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          providerType == other.providerType &&
          baseUrl == other.baseUrl &&
          modelName == other.modelName &&
          isActive == other.isActive &&
          createdAtMs == other.createdAtMs &&
          updatedAtMs == other.updatedAtMs;
}

class LlmUsageAggregate {
  final String purpose;
  final PlatformInt64 requests;
  final PlatformInt64 requestsWithUsage;
  final PlatformInt64 inputTokens;
  final PlatformInt64 outputTokens;
  final PlatformInt64 totalTokens;

  const LlmUsageAggregate({
    required this.purpose,
    required this.requests,
    required this.requestsWithUsage,
    required this.inputTokens,
    required this.outputTokens,
    required this.totalTokens,
  });

  @override
  int get hashCode =>
      purpose.hashCode ^
      requests.hashCode ^
      requestsWithUsage.hashCode ^
      inputTokens.hashCode ^
      outputTokens.hashCode ^
      totalTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LlmUsageAggregate &&
          runtimeType == other.runtimeType &&
          purpose == other.purpose &&
          requests == other.requests &&
          requestsWithUsage == other.requestsWithUsage &&
          inputTokens == other.inputTokens &&
          outputTokens == other.outputTokens &&
          totalTokens == other.totalTokens;
}

class Message {
  final String id;
  final String conversationId;
  final String role;
  final String content;
  final PlatformInt64 createdAtMs;
  final bool isMemory;

  const Message({
    required this.id,
    required this.conversationId,
    required this.role,
    required this.content,
    required this.createdAtMs,
    required this.isMemory,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      conversationId.hashCode ^
      role.hashCode ^
      content.hashCode ^
      createdAtMs.hashCode ^
      isMemory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Message &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          conversationId == other.conversationId &&
          role == other.role &&
          content == other.content &&
          createdAtMs == other.createdAtMs &&
          isMemory == other.isMemory;
}

class SimilarMessage {
  final Message message;
  final double distance;

  const SimilarMessage({
    required this.message,
    required this.distance,
  });

  @override
  int get hashCode => message.hashCode ^ distance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimilarMessage &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          distance == other.distance;
}

class SimilarTodoThread {
  final String todoId;
  final double distance;

  const SimilarTodoThread({
    required this.todoId,
    required this.distance,
  });

  @override
  int get hashCode => todoId.hashCode ^ distance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimilarTodoThread &&
          runtimeType == other.runtimeType &&
          todoId == other.todoId &&
          distance == other.distance;
}

class Todo {
  final String id;
  final String title;
  final PlatformInt64? dueAtMs;
  final String status;
  final String? sourceEntryId;
  final PlatformInt64 createdAtMs;
  final PlatformInt64 updatedAtMs;
  final PlatformInt64? reviewStage;
  final PlatformInt64? nextReviewAtMs;
  final PlatformInt64? lastReviewAtMs;

  const Todo({
    required this.id,
    required this.title,
    this.dueAtMs,
    required this.status,
    this.sourceEntryId,
    required this.createdAtMs,
    required this.updatedAtMs,
    this.reviewStage,
    this.nextReviewAtMs,
    this.lastReviewAtMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      dueAtMs.hashCode ^
      status.hashCode ^
      sourceEntryId.hashCode ^
      createdAtMs.hashCode ^
      updatedAtMs.hashCode ^
      reviewStage.hashCode ^
      nextReviewAtMs.hashCode ^
      lastReviewAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Todo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          dueAtMs == other.dueAtMs &&
          status == other.status &&
          sourceEntryId == other.sourceEntryId &&
          createdAtMs == other.createdAtMs &&
          updatedAtMs == other.updatedAtMs &&
          reviewStage == other.reviewStage &&
          nextReviewAtMs == other.nextReviewAtMs &&
          lastReviewAtMs == other.lastReviewAtMs;
}

class TodoActivity {
  final String id;
  final String todoId;
  final String activityType;
  final String? fromStatus;
  final String? toStatus;
  final String? content;
  final String? sourceMessageId;
  final PlatformInt64 createdAtMs;

  const TodoActivity({
    required this.id,
    required this.todoId,
    required this.activityType,
    this.fromStatus,
    this.toStatus,
    this.content,
    this.sourceMessageId,
    required this.createdAtMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      todoId.hashCode ^
      activityType.hashCode ^
      fromStatus.hashCode ^
      toStatus.hashCode ^
      content.hashCode ^
      sourceMessageId.hashCode ^
      createdAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoActivity &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          todoId == other.todoId &&
          activityType == other.activityType &&
          fromStatus == other.fromStatus &&
          toStatus == other.toStatus &&
          content == other.content &&
          sourceMessageId == other.sourceMessageId &&
          createdAtMs == other.createdAtMs;
}
