// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Conversation {
  final String id;
  final String title;
  final PlatformInt64 createdAtMs;
  final PlatformInt64 updatedAtMs;

  const Conversation({
    required this.id,
    required this.title,
    required this.createdAtMs,
    required this.updatedAtMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      createdAtMs.hashCode ^
      updatedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Conversation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          createdAtMs == other.createdAtMs &&
          updatedAtMs == other.updatedAtMs;
}

class Message {
  final String id;
  final String conversationId;
  final String role;
  final String content;
  final PlatformInt64 createdAtMs;

  const Message({
    required this.id,
    required this.conversationId,
    required this.role,
    required this.content,
    required this.createdAtMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      conversationId.hashCode ^
      role.hashCode ^
      content.hashCode ^
      createdAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Message &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          conversationId == other.conversationId &&
          role == other.role &&
          content == other.content &&
          createdAtMs == other.createdAtMs;
}

class SimilarMessage {
  final Message message;
  final double distance;

  const SimilarMessage({
    required this.message,
    required this.distance,
  });

  @override
  int get hashCode => message.hashCode ^ distance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimilarMessage &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          distance == other.distance;
}
