// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/core.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'db.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.html) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.0.0-dev.38';

  @override
  int get rustContentHash => -364250712;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'secondloop_rust',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<Uint8List> crateApiCoreAuthInitMasterPassword(
      {required String appDir, required String password});

  Future<bool> crateApiCoreAuthIsInitialized({required String appDir});

  Future<Uint8List> crateApiCoreAuthUnlockWithPassword(
      {required String appDir, required String password});

  Future<void> crateApiCoreAuthValidateKey(
      {required String appDir, required List<int> key});

  Future<Conversation> crateApiCoreDbCreateConversation(
      {required String appDir, required List<int> key, required String title});

  Future<Message> crateApiCoreDbInsertMessage(
      {required String appDir,
      required List<int> key,
      required String conversationId,
      required String role,
      required String content});

  Future<List<Conversation>> crateApiCoreDbListConversations(
      {required String appDir, required List<int> key});

  Future<List<Message>> crateApiCoreDbListMessages(
      {required String appDir,
      required List<int> key,
      required String conversationId});

  Future<int> crateApiCoreDbProcessPendingMessageEmbeddings(
      {required String appDir, required List<int> key, required int limit});

  Future<int> crateApiCoreDbRebuildMessageEmbeddings(
      {required String appDir,
      required List<int> key,
      required int batchLimit});

  Future<List<SimilarMessage>> crateApiCoreDbSearchSimilarMessages(
      {required String appDir,
      required List<int> key,
      required String query,
      required int topK});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Uint8List> crateApiCoreAuthInitMasterPassword(
      {required String appDir, required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreAuthInitMasterPasswordConstMeta,
      argValues: [appDir, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreAuthInitMasterPasswordConstMeta =>
      const TaskConstMeta(
        debugName: "auth_init_master_password",
        argNames: ["appDir", "password"],
      );

  @override
  Future<bool> crateApiCoreAuthIsInitialized({required String appDir}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCoreAuthIsInitializedConstMeta,
      argValues: [appDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreAuthIsInitializedConstMeta =>
      const TaskConstMeta(
        debugName: "auth_is_initialized",
        argNames: ["appDir"],
      );

  @override
  Future<Uint8List> crateApiCoreAuthUnlockWithPassword(
      {required String appDir, required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreAuthUnlockWithPasswordConstMeta,
      argValues: [appDir, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreAuthUnlockWithPasswordConstMeta =>
      const TaskConstMeta(
        debugName: "auth_unlock_with_password",
        argNames: ["appDir", "password"],
      );

  @override
  Future<void> crateApiCoreAuthValidateKey(
      {required String appDir, required List<int> key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreAuthValidateKeyConstMeta,
      argValues: [appDir, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreAuthValidateKeyConstMeta =>
      const TaskConstMeta(
        debugName: "auth_validate_key",
        argNames: ["appDir", "key"],
      );

  @override
  Future<Conversation> crateApiCoreDbCreateConversation(
      {required String appDir, required List<int> key, required String title}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_String(title, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_conversation,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbCreateConversationConstMeta,
      argValues: [appDir, key, title],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbCreateConversationConstMeta =>
      const TaskConstMeta(
        debugName: "db_create_conversation",
        argNames: ["appDir", "key", "title"],
      );

  @override
  Future<Message> crateApiCoreDbInsertMessage(
      {required String appDir,
      required List<int> key,
      required String conversationId,
      required String role,
      required String content}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_String(conversationId, serializer);
        sse_encode_String(role, serializer);
        sse_encode_String(content, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_message,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbInsertMessageConstMeta,
      argValues: [appDir, key, conversationId, role, content],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbInsertMessageConstMeta =>
      const TaskConstMeta(
        debugName: "db_insert_message",
        argNames: ["appDir", "key", "conversationId", "role", "content"],
      );

  @override
  Future<List<Conversation>> crateApiCoreDbListConversations(
      {required String appDir, required List<int> key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_conversation,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbListConversationsConstMeta,
      argValues: [appDir, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbListConversationsConstMeta =>
      const TaskConstMeta(
        debugName: "db_list_conversations",
        argNames: ["appDir", "key"],
      );

  @override
  Future<List<Message>> crateApiCoreDbListMessages(
      {required String appDir,
      required List<int> key,
      required String conversationId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_String(conversationId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_message,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbListMessagesConstMeta,
      argValues: [appDir, key, conversationId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbListMessagesConstMeta => const TaskConstMeta(
        debugName: "db_list_messages",
        argNames: ["appDir", "key", "conversationId"],
      );

  @override
  Future<int> crateApiCoreDbProcessPendingMessageEmbeddings(
      {required String appDir, required List<int> key, required int limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_u_32(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbProcessPendingMessageEmbeddingsConstMeta,
      argValues: [appDir, key, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbProcessPendingMessageEmbeddingsConstMeta =>
      const TaskConstMeta(
        debugName: "db_process_pending_message_embeddings",
        argNames: ["appDir", "key", "limit"],
      );

  @override
  Future<int> crateApiCoreDbRebuildMessageEmbeddings(
      {required String appDir,
      required List<int> key,
      required int batchLimit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_u_32(batchLimit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbRebuildMessageEmbeddingsConstMeta,
      argValues: [appDir, key, batchLimit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbRebuildMessageEmbeddingsConstMeta =>
      const TaskConstMeta(
        debugName: "db_rebuild_message_embeddings",
        argNames: ["appDir", "key", "batchLimit"],
      );

  @override
  Future<List<SimilarMessage>> crateApiCoreDbSearchSimilarMessages(
      {required String appDir,
      required List<int> key,
      required String query,
      required int topK}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_String(query, serializer);
        sse_encode_u_32(topK, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_similar_message,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbSearchSimilarMessagesConstMeta,
      argValues: [appDir, key, query, topK],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbSearchSimilarMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "db_search_similar_messages",
        argNames: ["appDir", "key", "query", "topK"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleGreetConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta => const TaskConstMeta(
        debugName: "greet",
        argNames: ["name"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Conversation dco_decode_conversation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Conversation(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      createdAtMs: dco_decode_i_64(arr[2]),
      updatedAtMs: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<Conversation> dco_decode_list_conversation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_conversation).toList();
  }

  @protected
  List<Message> dco_decode_list_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_message).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SimilarMessage> dco_decode_list_similar_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_similar_message).toList();
  }

  @protected
  Message dco_decode_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Message(
      id: dco_decode_String(arr[0]),
      conversationId: dco_decode_String(arr[1]),
      role: dco_decode_String(arr[2]),
      content: dco_decode_String(arr[3]),
      createdAtMs: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  SimilarMessage dco_decode_similar_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SimilarMessage(
      message: dco_decode_message(arr[0]),
      distance: dco_decode_f_64(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Conversation sse_decode_conversation(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_createdAtMs = sse_decode_i_64(deserializer);
    var var_updatedAtMs = sse_decode_i_64(deserializer);
    return Conversation(
        id: var_id,
        title: var_title,
        createdAtMs: var_createdAtMs,
        updatedAtMs: var_updatedAtMs);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<Conversation> sse_decode_list_conversation(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Conversation>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_conversation(deserializer));
    }
    return ans_;
  }

  @protected
  List<Message> sse_decode_list_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Message>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_message(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SimilarMessage> sse_decode_list_similar_message(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SimilarMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_similar_message(deserializer));
    }
    return ans_;
  }

  @protected
  Message sse_decode_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_conversationId = sse_decode_String(deserializer);
    var var_role = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_createdAtMs = sse_decode_i_64(deserializer);
    return Message(
        id: var_id,
        conversationId: var_conversationId,
        role: var_role,
        content: var_content,
        createdAtMs: var_createdAtMs);
  }

  @protected
  SimilarMessage sse_decode_similar_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_message = sse_decode_message(deserializer);
    var var_distance = sse_decode_f_64(deserializer);
    return SimilarMessage(message: var_message, distance: var_distance);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_conversation(Conversation self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_i_64(self.createdAtMs, serializer);
    sse_encode_i_64(self.updatedAtMs, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_conversation(
      List<Conversation> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_conversation(item, serializer);
    }
  }

  @protected
  void sse_encode_list_message(List<Message> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_similar_message(
      List<SimilarMessage> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_similar_message(item, serializer);
    }
  }

  @protected
  void sse_encode_message(Message self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.conversationId, serializer);
    sse_encode_String(self.role, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_i_64(self.createdAtMs, serializer);
  }

  @protected
  void sse_encode_similar_message(
      SimilarMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_message(self.message, serializer);
    sse_encode_f_64(self.distance, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
