// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/core.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'db.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.html) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.0.0-dev.38';

  @override
  int get rustContentHash => 185444152;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'secondloop_rust',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<Uint8List> crateApiCoreAuthInitMasterPassword(
      {required String appDir, required String password});

  Future<bool> crateApiCoreAuthIsInitialized({required String appDir});

  Future<Uint8List> crateApiCoreAuthUnlockWithPassword(
      {required String appDir, required String password});

  Future<void> crateApiCoreAuthValidateKey(
      {required String appDir, required List<int> key});

  Future<Conversation> crateApiCoreDbCreateConversation(
      {required String appDir, required List<int> key, required String title});

  Future<LlmProfile> crateApiCoreDbCreateLlmProfile(
      {required String appDir,
      required List<int> key,
      required String name,
      required String providerType,
      String? baseUrl,
      String? apiKey,
      required String modelName,
      required bool setActive});

  Future<void> crateApiCoreDbDeleteLlmProfile(
      {required String appDir,
      required List<int> key,
      required String profileId});

  Future<void> crateApiCoreDbEditMessage(
      {required String appDir,
      required List<int> key,
      required String messageId,
      required String content});

  Future<String> crateApiCoreDbGetActiveEmbeddingModelName(
      {required String appDir, required List<int> key});

  Future<Conversation> crateApiCoreDbGetOrCreateMainStreamConversation(
      {required String appDir, required List<int> key});

  Future<Attachment> crateApiCoreDbInsertAttachment(
      {required String appDir,
      required List<int> key,
      required List<int> bytes,
      required String mimeType});

  Future<Message> crateApiCoreDbInsertMessage(
      {required String appDir,
      required List<int> key,
      required String conversationId,
      required String role,
      required String content});

  Future<void> crateApiCoreDbLinkAttachmentToMessage(
      {required String appDir,
      required List<int> key,
      required String messageId,
      required String attachmentSha256});

  Future<List<Conversation>> crateApiCoreDbListConversations(
      {required String appDir, required List<int> key});

  Future<List<String>> crateApiCoreDbListEmbeddingModelNames(
      {required String appDir, required List<int> key});

  Future<List<LlmProfile>> crateApiCoreDbListLlmProfiles(
      {required String appDir, required List<int> key});

  Future<List<Attachment>> crateApiCoreDbListMessageAttachments(
      {required String appDir,
      required List<int> key,
      required String messageId});

  Future<List<Message>> crateApiCoreDbListMessages(
      {required String appDir,
      required List<int> key,
      required String conversationId});

  Future<int> crateApiCoreDbProcessPendingMessageEmbeddings(
      {required String appDir, required List<int> key, required int limit});

  Future<Uint8List> crateApiCoreDbReadAttachmentBytes(
      {required String appDir, required List<int> key, required String sha256});

  Future<int> crateApiCoreDbRebuildMessageEmbeddings(
      {required String appDir,
      required List<int> key,
      required int batchLimit});

  Future<void> crateApiCoreDbResetVaultDataPreservingLlmProfiles(
      {required String appDir, required List<int> key});

  Future<List<SimilarMessage>> crateApiCoreDbSearchSimilarMessages(
      {required String appDir,
      required List<int> key,
      required String query,
      required int topK});

  Future<bool> crateApiCoreDbSetActiveEmbeddingModelName(
      {required String appDir,
      required List<int> key,
      required String modelName});

  Future<void> crateApiCoreDbSetActiveLlmProfile(
      {required String appDir,
      required List<int> key,
      required String profileId});

  Future<void> crateApiCoreDbSetMessageDeleted(
      {required String appDir,
      required List<int> key,
      required String messageId,
      required bool isDeleted});

  Stream<String> crateApiCoreRagAskAiStream(
      {required String appDir,
      required List<int> key,
      required String conversationId,
      required String question,
      required int topK,
      required bool thisThreadOnly});

  Stream<String> crateApiCoreRagAskAiStreamCloudGateway(
      {required String appDir,
      required List<int> key,
      required String conversationId,
      required String question,
      required int topK,
      required bool thisThreadOnly,
      required String gatewayBaseUrl,
      required String firebaseIdToken,
      required String modelName});

  Future<Uint8List> crateApiCoreSyncDeriveKey({required String passphrase});

  Future<void> crateApiCoreSyncLocaldirClearRemoteRoot(
      {required String localDir, required String remoteRoot});

  Future<BigInt> crateApiCoreSyncLocaldirPull(
      {required String appDir,
      required List<int> key,
      required List<int> syncKey,
      required String localDir,
      required String remoteRoot});

  Future<BigInt> crateApiCoreSyncLocaldirPush(
      {required String appDir,
      required List<int> key,
      required List<int> syncKey,
      required String localDir,
      required String remoteRoot});

  Future<void> crateApiCoreSyncLocaldirTestConnection(
      {required String localDir, required String remoteRoot});

  Future<BigInt> crateApiCoreSyncManagedVaultPull(
      {required String appDir,
      required List<int> key,
      required List<int> syncKey,
      required String baseUrl,
      required String vaultId,
      required String firebaseIdToken});

  Future<BigInt> crateApiCoreSyncManagedVaultPush(
      {required String appDir,
      required List<int> key,
      required List<int> syncKey,
      required String baseUrl,
      required String vaultId,
      required String firebaseIdToken});

  Future<void> crateApiCoreSyncWebdavClearRemoteRoot(
      {required String baseUrl,
      String? username,
      String? password,
      required String remoteRoot});

  Future<BigInt> crateApiCoreSyncWebdavPull(
      {required String appDir,
      required List<int> key,
      required List<int> syncKey,
      required String baseUrl,
      String? username,
      String? password,
      required String remoteRoot});

  Future<BigInt> crateApiCoreSyncWebdavPush(
      {required String appDir,
      required List<int> key,
      required List<int> syncKey,
      required String baseUrl,
      String? username,
      String? password,
      required String remoteRoot});

  Future<void> crateApiCoreSyncWebdavTestConnection(
      {required String baseUrl,
      String? username,
      String? password,
      required String remoteRoot});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Uint8List> crateApiCoreAuthInitMasterPassword(
      {required String appDir, required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreAuthInitMasterPasswordConstMeta,
      argValues: [appDir, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreAuthInitMasterPasswordConstMeta =>
      const TaskConstMeta(
        debugName: "auth_init_master_password",
        argNames: ["appDir", "password"],
      );

  @override
  Future<bool> crateApiCoreAuthIsInitialized({required String appDir}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCoreAuthIsInitializedConstMeta,
      argValues: [appDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreAuthIsInitializedConstMeta =>
      const TaskConstMeta(
        debugName: "auth_is_initialized",
        argNames: ["appDir"],
      );

  @override
  Future<Uint8List> crateApiCoreAuthUnlockWithPassword(
      {required String appDir, required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreAuthUnlockWithPasswordConstMeta,
      argValues: [appDir, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreAuthUnlockWithPasswordConstMeta =>
      const TaskConstMeta(
        debugName: "auth_unlock_with_password",
        argNames: ["appDir", "password"],
      );

  @override
  Future<void> crateApiCoreAuthValidateKey(
      {required String appDir, required List<int> key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreAuthValidateKeyConstMeta,
      argValues: [appDir, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreAuthValidateKeyConstMeta =>
      const TaskConstMeta(
        debugName: "auth_validate_key",
        argNames: ["appDir", "key"],
      );

  @override
  Future<Conversation> crateApiCoreDbCreateConversation(
      {required String appDir, required List<int> key, required String title}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_String(title, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_conversation,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbCreateConversationConstMeta,
      argValues: [appDir, key, title],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbCreateConversationConstMeta =>
      const TaskConstMeta(
        debugName: "db_create_conversation",
        argNames: ["appDir", "key", "title"],
      );

  @override
  Future<LlmProfile> crateApiCoreDbCreateLlmProfile(
      {required String appDir,
      required List<int> key,
      required String name,
      required String providerType,
      String? baseUrl,
      String? apiKey,
      required String modelName,
      required bool setActive}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_String(name, serializer);
        sse_encode_String(providerType, serializer);
        sse_encode_opt_String(baseUrl, serializer);
        sse_encode_opt_String(apiKey, serializer);
        sse_encode_String(modelName, serializer);
        sse_encode_bool(setActive, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_llm_profile,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbCreateLlmProfileConstMeta,
      argValues: [
        appDir,
        key,
        name,
        providerType,
        baseUrl,
        apiKey,
        modelName,
        setActive
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbCreateLlmProfileConstMeta =>
      const TaskConstMeta(
        debugName: "db_create_llm_profile",
        argNames: [
          "appDir",
          "key",
          "name",
          "providerType",
          "baseUrl",
          "apiKey",
          "modelName",
          "setActive"
        ],
      );

  @override
  Future<void> crateApiCoreDbDeleteLlmProfile(
      {required String appDir,
      required List<int> key,
      required String profileId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_String(profileId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbDeleteLlmProfileConstMeta,
      argValues: [appDir, key, profileId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbDeleteLlmProfileConstMeta =>
      const TaskConstMeta(
        debugName: "db_delete_llm_profile",
        argNames: ["appDir", "key", "profileId"],
      );

  @override
  Future<void> crateApiCoreDbEditMessage(
      {required String appDir,
      required List<int> key,
      required String messageId,
      required String content}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_String(messageId, serializer);
        sse_encode_String(content, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbEditMessageConstMeta,
      argValues: [appDir, key, messageId, content],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbEditMessageConstMeta => const TaskConstMeta(
        debugName: "db_edit_message",
        argNames: ["appDir", "key", "messageId", "content"],
      );

  @override
  Future<String> crateApiCoreDbGetActiveEmbeddingModelName(
      {required String appDir, required List<int> key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbGetActiveEmbeddingModelNameConstMeta,
      argValues: [appDir, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbGetActiveEmbeddingModelNameConstMeta =>
      const TaskConstMeta(
        debugName: "db_get_active_embedding_model_name",
        argNames: ["appDir", "key"],
      );

  @override
  Future<Conversation> crateApiCoreDbGetOrCreateMainStreamConversation(
      {required String appDir, required List<int> key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_conversation,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbGetOrCreateMainStreamConversationConstMeta,
      argValues: [appDir, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbGetOrCreateMainStreamConversationConstMeta =>
      const TaskConstMeta(
        debugName: "db_get_or_create_main_stream_conversation",
        argNames: ["appDir", "key"],
      );

  @override
  Future<Attachment> crateApiCoreDbInsertAttachment(
      {required String appDir,
      required List<int> key,
      required List<int> bytes,
      required String mimeType}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        sse_encode_String(mimeType, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_attachment,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbInsertAttachmentConstMeta,
      argValues: [appDir, key, bytes, mimeType],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbInsertAttachmentConstMeta =>
      const TaskConstMeta(
        debugName: "db_insert_attachment",
        argNames: ["appDir", "key", "bytes", "mimeType"],
      );

  @override
  Future<Message> crateApiCoreDbInsertMessage(
      {required String appDir,
      required List<int> key,
      required String conversationId,
      required String role,
      required String content}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_String(conversationId, serializer);
        sse_encode_String(role, serializer);
        sse_encode_String(content, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_message,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbInsertMessageConstMeta,
      argValues: [appDir, key, conversationId, role, content],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbInsertMessageConstMeta =>
      const TaskConstMeta(
        debugName: "db_insert_message",
        argNames: ["appDir", "key", "conversationId", "role", "content"],
      );

  @override
  Future<void> crateApiCoreDbLinkAttachmentToMessage(
      {required String appDir,
      required List<int> key,
      required String messageId,
      required String attachmentSha256}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_String(messageId, serializer);
        sse_encode_String(attachmentSha256, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbLinkAttachmentToMessageConstMeta,
      argValues: [appDir, key, messageId, attachmentSha256],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbLinkAttachmentToMessageConstMeta =>
      const TaskConstMeta(
        debugName: "db_link_attachment_to_message",
        argNames: ["appDir", "key", "messageId", "attachmentSha256"],
      );

  @override
  Future<List<Conversation>> crateApiCoreDbListConversations(
      {required String appDir, required List<int> key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_conversation,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbListConversationsConstMeta,
      argValues: [appDir, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbListConversationsConstMeta =>
      const TaskConstMeta(
        debugName: "db_list_conversations",
        argNames: ["appDir", "key"],
      );

  @override
  Future<List<String>> crateApiCoreDbListEmbeddingModelNames(
      {required String appDir, required List<int> key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbListEmbeddingModelNamesConstMeta,
      argValues: [appDir, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbListEmbeddingModelNamesConstMeta =>
      const TaskConstMeta(
        debugName: "db_list_embedding_model_names",
        argNames: ["appDir", "key"],
      );

  @override
  Future<List<LlmProfile>> crateApiCoreDbListLlmProfiles(
      {required String appDir, required List<int> key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_llm_profile,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbListLlmProfilesConstMeta,
      argValues: [appDir, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbListLlmProfilesConstMeta =>
      const TaskConstMeta(
        debugName: "db_list_llm_profiles",
        argNames: ["appDir", "key"],
      );

  @override
  Future<List<Attachment>> crateApiCoreDbListMessageAttachments(
      {required String appDir,
      required List<int> key,
      required String messageId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_String(messageId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_attachment,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbListMessageAttachmentsConstMeta,
      argValues: [appDir, key, messageId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbListMessageAttachmentsConstMeta =>
      const TaskConstMeta(
        debugName: "db_list_message_attachments",
        argNames: ["appDir", "key", "messageId"],
      );

  @override
  Future<List<Message>> crateApiCoreDbListMessages(
      {required String appDir,
      required List<int> key,
      required String conversationId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_String(conversationId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_message,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbListMessagesConstMeta,
      argValues: [appDir, key, conversationId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbListMessagesConstMeta => const TaskConstMeta(
        debugName: "db_list_messages",
        argNames: ["appDir", "key", "conversationId"],
      );

  @override
  Future<int> crateApiCoreDbProcessPendingMessageEmbeddings(
      {required String appDir, required List<int> key, required int limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_u_32(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbProcessPendingMessageEmbeddingsConstMeta,
      argValues: [appDir, key, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbProcessPendingMessageEmbeddingsConstMeta =>
      const TaskConstMeta(
        debugName: "db_process_pending_message_embeddings",
        argNames: ["appDir", "key", "limit"],
      );

  @override
  Future<Uint8List> crateApiCoreDbReadAttachmentBytes(
      {required String appDir,
      required List<int> key,
      required String sha256}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_String(sha256, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbReadAttachmentBytesConstMeta,
      argValues: [appDir, key, sha256],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbReadAttachmentBytesConstMeta =>
      const TaskConstMeta(
        debugName: "db_read_attachment_bytes",
        argNames: ["appDir", "key", "sha256"],
      );

  @override
  Future<int> crateApiCoreDbRebuildMessageEmbeddings(
      {required String appDir,
      required List<int> key,
      required int batchLimit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_u_32(batchLimit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbRebuildMessageEmbeddingsConstMeta,
      argValues: [appDir, key, batchLimit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbRebuildMessageEmbeddingsConstMeta =>
      const TaskConstMeta(
        debugName: "db_rebuild_message_embeddings",
        argNames: ["appDir", "key", "batchLimit"],
      );

  @override
  Future<void> crateApiCoreDbResetVaultDataPreservingLlmProfiles(
      {required String appDir, required List<int> key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbResetVaultDataPreservingLlmProfilesConstMeta,
      argValues: [appDir, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiCoreDbResetVaultDataPreservingLlmProfilesConstMeta =>
          const TaskConstMeta(
            debugName: "db_reset_vault_data_preserving_llm_profiles",
            argNames: ["appDir", "key"],
          );

  @override
  Future<List<SimilarMessage>> crateApiCoreDbSearchSimilarMessages(
      {required String appDir,
      required List<int> key,
      required String query,
      required int topK}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_String(query, serializer);
        sse_encode_u_32(topK, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_similar_message,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbSearchSimilarMessagesConstMeta,
      argValues: [appDir, key, query, topK],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbSearchSimilarMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "db_search_similar_messages",
        argNames: ["appDir", "key", "query", "topK"],
      );

  @override
  Future<bool> crateApiCoreDbSetActiveEmbeddingModelName(
      {required String appDir,
      required List<int> key,
      required String modelName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_String(modelName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbSetActiveEmbeddingModelNameConstMeta,
      argValues: [appDir, key, modelName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbSetActiveEmbeddingModelNameConstMeta =>
      const TaskConstMeta(
        debugName: "db_set_active_embedding_model_name",
        argNames: ["appDir", "key", "modelName"],
      );

  @override
  Future<void> crateApiCoreDbSetActiveLlmProfile(
      {required String appDir,
      required List<int> key,
      required String profileId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_String(profileId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbSetActiveLlmProfileConstMeta,
      argValues: [appDir, key, profileId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbSetActiveLlmProfileConstMeta =>
      const TaskConstMeta(
        debugName: "db_set_active_llm_profile",
        argNames: ["appDir", "key", "profileId"],
      );

  @override
  Future<void> crateApiCoreDbSetMessageDeleted(
      {required String appDir,
      required List<int> key,
      required String messageId,
      required bool isDeleted}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_String(messageId, serializer);
        sse_encode_bool(isDeleted, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreDbSetMessageDeletedConstMeta,
      argValues: [appDir, key, messageId, isDeleted],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreDbSetMessageDeletedConstMeta =>
      const TaskConstMeta(
        debugName: "db_set_message_deleted",
        argNames: ["appDir", "key", "messageId", "isDeleted"],
      );

  @override
  Stream<String> crateApiCoreRagAskAiStream(
      {required String appDir,
      required List<int> key,
      required String conversationId,
      required String question,
      required int topK,
      required bool thisThreadOnly}) {
    final sink = RustStreamSink<String>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_String(conversationId, serializer);
        sse_encode_String(question, serializer);
        sse_encode_u_32(topK, serializer);
        sse_encode_bool(thisThreadOnly, serializer);
        sse_encode_StreamSink_String_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreRagAskAiStreamConstMeta,
      argValues: [
        appDir,
        key,
        conversationId,
        question,
        topK,
        thisThreadOnly,
        sink
      ],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiCoreRagAskAiStreamConstMeta => const TaskConstMeta(
        debugName: "rag_ask_ai_stream",
        argNames: [
          "appDir",
          "key",
          "conversationId",
          "question",
          "topK",
          "thisThreadOnly",
          "sink"
        ],
      );

  @override
  Stream<String> crateApiCoreRagAskAiStreamCloudGateway(
      {required String appDir,
      required List<int> key,
      required String conversationId,
      required String question,
      required int topK,
      required bool thisThreadOnly,
      required String gatewayBaseUrl,
      required String firebaseIdToken,
      required String modelName}) {
    final sink = RustStreamSink<String>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_String(conversationId, serializer);
        sse_encode_String(question, serializer);
        sse_encode_u_32(topK, serializer);
        sse_encode_bool(thisThreadOnly, serializer);
        sse_encode_String(gatewayBaseUrl, serializer);
        sse_encode_String(firebaseIdToken, serializer);
        sse_encode_String(modelName, serializer);
        sse_encode_StreamSink_String_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 28, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreRagAskAiStreamCloudGatewayConstMeta,
      argValues: [
        appDir,
        key,
        conversationId,
        question,
        topK,
        thisThreadOnly,
        gatewayBaseUrl,
        firebaseIdToken,
        modelName,
        sink
      ],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiCoreRagAskAiStreamCloudGatewayConstMeta =>
      const TaskConstMeta(
        debugName: "rag_ask_ai_stream_cloud_gateway",
        argNames: [
          "appDir",
          "key",
          "conversationId",
          "question",
          "topK",
          "thisThreadOnly",
          "gatewayBaseUrl",
          "firebaseIdToken",
          "modelName",
          "sink"
        ],
      );

  @override
  Future<Uint8List> crateApiCoreSyncDeriveKey({required String passphrase}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(passphrase, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreSyncDeriveKeyConstMeta,
      argValues: [passphrase],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreSyncDeriveKeyConstMeta => const TaskConstMeta(
        debugName: "sync_derive_key",
        argNames: ["passphrase"],
      );

  @override
  Future<void> crateApiCoreSyncLocaldirClearRemoteRoot(
      {required String localDir, required String remoteRoot}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(localDir, serializer);
        sse_encode_String(remoteRoot, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 30, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreSyncLocaldirClearRemoteRootConstMeta,
      argValues: [localDir, remoteRoot],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreSyncLocaldirClearRemoteRootConstMeta =>
      const TaskConstMeta(
        debugName: "sync_localdir_clear_remote_root",
        argNames: ["localDir", "remoteRoot"],
      );

  @override
  Future<BigInt> crateApiCoreSyncLocaldirPull(
      {required String appDir,
      required List<int> key,
      required List<int> syncKey,
      required String localDir,
      required String remoteRoot}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_list_prim_u_8_loose(syncKey, serializer);
        sse_encode_String(localDir, serializer);
        sse_encode_String(remoteRoot, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 31, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreSyncLocaldirPullConstMeta,
      argValues: [appDir, key, syncKey, localDir, remoteRoot],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreSyncLocaldirPullConstMeta =>
      const TaskConstMeta(
        debugName: "sync_localdir_pull",
        argNames: ["appDir", "key", "syncKey", "localDir", "remoteRoot"],
      );

  @override
  Future<BigInt> crateApiCoreSyncLocaldirPush(
      {required String appDir,
      required List<int> key,
      required List<int> syncKey,
      required String localDir,
      required String remoteRoot}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_list_prim_u_8_loose(syncKey, serializer);
        sse_encode_String(localDir, serializer);
        sse_encode_String(remoteRoot, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 32, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreSyncLocaldirPushConstMeta,
      argValues: [appDir, key, syncKey, localDir, remoteRoot],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreSyncLocaldirPushConstMeta =>
      const TaskConstMeta(
        debugName: "sync_localdir_push",
        argNames: ["appDir", "key", "syncKey", "localDir", "remoteRoot"],
      );

  @override
  Future<void> crateApiCoreSyncLocaldirTestConnection(
      {required String localDir, required String remoteRoot}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(localDir, serializer);
        sse_encode_String(remoteRoot, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 33, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreSyncLocaldirTestConnectionConstMeta,
      argValues: [localDir, remoteRoot],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreSyncLocaldirTestConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "sync_localdir_test_connection",
        argNames: ["localDir", "remoteRoot"],
      );

  @override
  Future<BigInt> crateApiCoreSyncManagedVaultPull(
      {required String appDir,
      required List<int> key,
      required List<int> syncKey,
      required String baseUrl,
      required String vaultId,
      required String firebaseIdToken}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_list_prim_u_8_loose(syncKey, serializer);
        sse_encode_String(baseUrl, serializer);
        sse_encode_String(vaultId, serializer);
        sse_encode_String(firebaseIdToken, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 34, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreSyncManagedVaultPullConstMeta,
      argValues: [appDir, key, syncKey, baseUrl, vaultId, firebaseIdToken],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreSyncManagedVaultPullConstMeta =>
      const TaskConstMeta(
        debugName: "sync_managed_vault_pull",
        argNames: [
          "appDir",
          "key",
          "syncKey",
          "baseUrl",
          "vaultId",
          "firebaseIdToken"
        ],
      );

  @override
  Future<BigInt> crateApiCoreSyncManagedVaultPush(
      {required String appDir,
      required List<int> key,
      required List<int> syncKey,
      required String baseUrl,
      required String vaultId,
      required String firebaseIdToken}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_list_prim_u_8_loose(syncKey, serializer);
        sse_encode_String(baseUrl, serializer);
        sse_encode_String(vaultId, serializer);
        sse_encode_String(firebaseIdToken, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 35, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreSyncManagedVaultPushConstMeta,
      argValues: [appDir, key, syncKey, baseUrl, vaultId, firebaseIdToken],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreSyncManagedVaultPushConstMeta =>
      const TaskConstMeta(
        debugName: "sync_managed_vault_push",
        argNames: [
          "appDir",
          "key",
          "syncKey",
          "baseUrl",
          "vaultId",
          "firebaseIdToken"
        ],
      );

  @override
  Future<void> crateApiCoreSyncWebdavClearRemoteRoot(
      {required String baseUrl,
      String? username,
      String? password,
      required String remoteRoot}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(baseUrl, serializer);
        sse_encode_opt_String(username, serializer);
        sse_encode_opt_String(password, serializer);
        sse_encode_String(remoteRoot, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 36, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreSyncWebdavClearRemoteRootConstMeta,
      argValues: [baseUrl, username, password, remoteRoot],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreSyncWebdavClearRemoteRootConstMeta =>
      const TaskConstMeta(
        debugName: "sync_webdav_clear_remote_root",
        argNames: ["baseUrl", "username", "password", "remoteRoot"],
      );

  @override
  Future<BigInt> crateApiCoreSyncWebdavPull(
      {required String appDir,
      required List<int> key,
      required List<int> syncKey,
      required String baseUrl,
      String? username,
      String? password,
      required String remoteRoot}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_list_prim_u_8_loose(syncKey, serializer);
        sse_encode_String(baseUrl, serializer);
        sse_encode_opt_String(username, serializer);
        sse_encode_opt_String(password, serializer);
        sse_encode_String(remoteRoot, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 37, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreSyncWebdavPullConstMeta,
      argValues: [
        appDir,
        key,
        syncKey,
        baseUrl,
        username,
        password,
        remoteRoot
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreSyncWebdavPullConstMeta => const TaskConstMeta(
        debugName: "sync_webdav_pull",
        argNames: [
          "appDir",
          "key",
          "syncKey",
          "baseUrl",
          "username",
          "password",
          "remoteRoot"
        ],
      );

  @override
  Future<BigInt> crateApiCoreSyncWebdavPush(
      {required String appDir,
      required List<int> key,
      required List<int> syncKey,
      required String baseUrl,
      String? username,
      String? password,
      required String remoteRoot}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_list_prim_u_8_loose(syncKey, serializer);
        sse_encode_String(baseUrl, serializer);
        sse_encode_opt_String(username, serializer);
        sse_encode_opt_String(password, serializer);
        sse_encode_String(remoteRoot, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 38, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreSyncWebdavPushConstMeta,
      argValues: [
        appDir,
        key,
        syncKey,
        baseUrl,
        username,
        password,
        remoteRoot
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreSyncWebdavPushConstMeta => const TaskConstMeta(
        debugName: "sync_webdav_push",
        argNames: [
          "appDir",
          "key",
          "syncKey",
          "baseUrl",
          "username",
          "password",
          "remoteRoot"
        ],
      );

  @override
  Future<void> crateApiCoreSyncWebdavTestConnection(
      {required String baseUrl,
      String? username,
      String? password,
      required String remoteRoot}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(baseUrl, serializer);
        sse_encode_opt_String(username, serializer);
        sse_encode_opt_String(password, serializer);
        sse_encode_String(remoteRoot, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 39, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreSyncWebdavTestConnectionConstMeta,
      argValues: [baseUrl, username, password, remoteRoot],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreSyncWebdavTestConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "sync_webdav_test_connection",
        argNames: ["baseUrl", "username", "password", "remoteRoot"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 40)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleGreetConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta => const TaskConstMeta(
        debugName: "greet",
        argNames: ["name"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 41, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Attachment dco_decode_attachment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Attachment(
      sha256: dco_decode_String(arr[0]),
      mimeType: dco_decode_String(arr[1]),
      path: dco_decode_String(arr[2]),
      byteLen: dco_decode_i_64(arr[3]),
      createdAtMs: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Conversation dco_decode_conversation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Conversation(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      createdAtMs: dco_decode_i_64(arr[2]),
      updatedAtMs: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Attachment> dco_decode_list_attachment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_attachment).toList();
  }

  @protected
  List<Conversation> dco_decode_list_conversation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_conversation).toList();
  }

  @protected
  List<LlmProfile> dco_decode_list_llm_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_llm_profile).toList();
  }

  @protected
  List<Message> dco_decode_list_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_message).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SimilarMessage> dco_decode_list_similar_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_similar_message).toList();
  }

  @protected
  LlmProfile dco_decode_llm_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return LlmProfile(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      providerType: dco_decode_String(arr[2]),
      baseUrl: dco_decode_opt_String(arr[3]),
      modelName: dco_decode_String(arr[4]),
      isActive: dco_decode_bool(arr[5]),
      createdAtMs: dco_decode_i_64(arr[6]),
      updatedAtMs: dco_decode_i_64(arr[7]),
    );
  }

  @protected
  Message dco_decode_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Message(
      id: dco_decode_String(arr[0]),
      conversationId: dco_decode_String(arr[1]),
      role: dco_decode_String(arr[2]),
      content: dco_decode_String(arr[3]),
      createdAtMs: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  SimilarMessage dco_decode_similar_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SimilarMessage(
      message: dco_decode_message(arr[0]),
      distance: dco_decode_f_64(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Attachment sse_decode_attachment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sha256 = sse_decode_String(deserializer);
    var var_mimeType = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_byteLen = sse_decode_i_64(deserializer);
    var var_createdAtMs = sse_decode_i_64(deserializer);
    return Attachment(
        sha256: var_sha256,
        mimeType: var_mimeType,
        path: var_path,
        byteLen: var_byteLen,
        createdAtMs: var_createdAtMs);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Conversation sse_decode_conversation(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_createdAtMs = sse_decode_i_64(deserializer);
    var var_updatedAtMs = sse_decode_i_64(deserializer);
    return Conversation(
        id: var_id,
        title: var_title,
        createdAtMs: var_createdAtMs,
        updatedAtMs: var_updatedAtMs);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Attachment> sse_decode_list_attachment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Attachment>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_attachment(deserializer));
    }
    return ans_;
  }

  @protected
  List<Conversation> sse_decode_list_conversation(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Conversation>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_conversation(deserializer));
    }
    return ans_;
  }

  @protected
  List<LlmProfile> sse_decode_list_llm_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LlmProfile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_llm_profile(deserializer));
    }
    return ans_;
  }

  @protected
  List<Message> sse_decode_list_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Message>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_message(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SimilarMessage> sse_decode_list_similar_message(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SimilarMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_similar_message(deserializer));
    }
    return ans_;
  }

  @protected
  LlmProfile sse_decode_llm_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_providerType = sse_decode_String(deserializer);
    var var_baseUrl = sse_decode_opt_String(deserializer);
    var var_modelName = sse_decode_String(deserializer);
    var var_isActive = sse_decode_bool(deserializer);
    var var_createdAtMs = sse_decode_i_64(deserializer);
    var var_updatedAtMs = sse_decode_i_64(deserializer);
    return LlmProfile(
        id: var_id,
        name: var_name,
        providerType: var_providerType,
        baseUrl: var_baseUrl,
        modelName: var_modelName,
        isActive: var_isActive,
        createdAtMs: var_createdAtMs,
        updatedAtMs: var_updatedAtMs);
  }

  @protected
  Message sse_decode_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_conversationId = sse_decode_String(deserializer);
    var var_role = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_createdAtMs = sse_decode_i_64(deserializer);
    return Message(
        id: var_id,
        conversationId: var_conversationId,
        role: var_role,
        content: var_content,
        createdAtMs: var_createdAtMs);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SimilarMessage sse_decode_similar_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_message = sse_decode_message(deserializer);
    var var_distance = sse_decode_f_64(deserializer);
    return SimilarMessage(message: var_message, distance: var_distance);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
      RustStreamSink<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
                decodeSuccessData: sse_decode_String, decodeErrorData: null)),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_attachment(Attachment self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sha256, serializer);
    sse_encode_String(self.mimeType, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_i_64(self.byteLen, serializer);
    sse_encode_i_64(self.createdAtMs, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_conversation(Conversation self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_i_64(self.createdAtMs, serializer);
    sse_encode_i_64(self.updatedAtMs, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_attachment(
      List<Attachment> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_attachment(item, serializer);
    }
  }

  @protected
  void sse_encode_list_conversation(
      List<Conversation> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_conversation(item, serializer);
    }
  }

  @protected
  void sse_encode_list_llm_profile(
      List<LlmProfile> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_llm_profile(item, serializer);
    }
  }

  @protected
  void sse_encode_list_message(List<Message> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_similar_message(
      List<SimilarMessage> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_similar_message(item, serializer);
    }
  }

  @protected
  void sse_encode_llm_profile(LlmProfile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.providerType, serializer);
    sse_encode_opt_String(self.baseUrl, serializer);
    sse_encode_String(self.modelName, serializer);
    sse_encode_bool(self.isActive, serializer);
    sse_encode_i_64(self.createdAtMs, serializer);
    sse_encode_i_64(self.updatedAtMs, serializer);
  }

  @protected
  void sse_encode_message(Message self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.conversationId, serializer);
    sse_encode_String(self.role, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_i_64(self.createdAtMs, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_similar_message(
      SimilarMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_message(self.message, serializer);
    sse_encode_f_64(self.distance, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
