// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/core.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'db.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Attachment dco_decode_attachment(dynamic raw);

  @protected
  AttachmentVariant dco_decode_attachment_variant(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  CloudMediaBackup dco_decode_cloud_media_backup(dynamic raw);

  @protected
  CloudMediaBackupSummary dco_decode_cloud_media_backup_summary(dynamic raw);

  @protected
  Conversation dco_decode_conversation(dynamic raw);

  @protected
  Event dco_decode_event(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Attachment> dco_decode_list_attachment(dynamic raw);

  @protected
  List<CloudMediaBackup> dco_decode_list_cloud_media_backup(dynamic raw);

  @protected
  List<Conversation> dco_decode_list_conversation(dynamic raw);

  @protected
  List<Event> dco_decode_list_event(dynamic raw);

  @protected
  List<LlmProfile> dco_decode_list_llm_profile(dynamic raw);

  @protected
  List<LlmUsageAggregate> dco_decode_list_llm_usage_aggregate(dynamic raw);

  @protected
  List<Message> dco_decode_list_message(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SimilarMessage> dco_decode_list_similar_message(dynamic raw);

  @protected
  List<SimilarTodoThread> dco_decode_list_similar_todo_thread(dynamic raw);

  @protected
  List<Todo> dco_decode_list_todo(dynamic raw);

  @protected
  List<TodoActivity> dco_decode_list_todo_activity(dynamic raw);

  @protected
  LlmProfile dco_decode_llm_profile(dynamic raw);

  @protected
  LlmUsageAggregate dco_decode_llm_usage_aggregate(dynamic raw);

  @protected
  Message dco_decode_message(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  SimilarMessage dco_decode_similar_message(dynamic raw);

  @protected
  SimilarTodoThread dco_decode_similar_todo_thread(dynamic raw);

  @protected
  Todo dco_decode_todo(dynamic raw);

  @protected
  TodoActivity dco_decode_todo_activity(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Attachment sse_decode_attachment(SseDeserializer deserializer);

  @protected
  AttachmentVariant sse_decode_attachment_variant(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  CloudMediaBackup sse_decode_cloud_media_backup(SseDeserializer deserializer);

  @protected
  CloudMediaBackupSummary sse_decode_cloud_media_backup_summary(
      SseDeserializer deserializer);

  @protected
  Conversation sse_decode_conversation(SseDeserializer deserializer);

  @protected
  Event sse_decode_event(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Attachment> sse_decode_list_attachment(SseDeserializer deserializer);

  @protected
  List<CloudMediaBackup> sse_decode_list_cloud_media_backup(
      SseDeserializer deserializer);

  @protected
  List<Conversation> sse_decode_list_conversation(SseDeserializer deserializer);

  @protected
  List<Event> sse_decode_list_event(SseDeserializer deserializer);

  @protected
  List<LlmProfile> sse_decode_list_llm_profile(SseDeserializer deserializer);

  @protected
  List<LlmUsageAggregate> sse_decode_list_llm_usage_aggregate(
      SseDeserializer deserializer);

  @protected
  List<Message> sse_decode_list_message(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SimilarMessage> sse_decode_list_similar_message(
      SseDeserializer deserializer);

  @protected
  List<SimilarTodoThread> sse_decode_list_similar_todo_thread(
      SseDeserializer deserializer);

  @protected
  List<Todo> sse_decode_list_todo(SseDeserializer deserializer);

  @protected
  List<TodoActivity> sse_decode_list_todo_activity(
      SseDeserializer deserializer);

  @protected
  LlmProfile sse_decode_llm_profile(SseDeserializer deserializer);

  @protected
  LlmUsageAggregate sse_decode_llm_usage_aggregate(
      SseDeserializer deserializer);

  @protected
  Message sse_decode_message(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SimilarMessage sse_decode_similar_message(SseDeserializer deserializer);

  @protected
  SimilarTodoThread sse_decode_similar_todo_thread(
      SseDeserializer deserializer);

  @protected
  Todo sse_decode_todo(SseDeserializer deserializer);

  @protected
  TodoActivity sse_decode_todo_activity(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_String_Sse(
      RustStreamSink<String> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_attachment(Attachment self, SseSerializer serializer);

  @protected
  void sse_encode_attachment_variant(
      AttachmentVariant self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_cloud_media_backup(
      CloudMediaBackup self, SseSerializer serializer);

  @protected
  void sse_encode_cloud_media_backup_summary(
      CloudMediaBackupSummary self, SseSerializer serializer);

  @protected
  void sse_encode_conversation(Conversation self, SseSerializer serializer);

  @protected
  void sse_encode_event(Event self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_attachment(
      List<Attachment> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cloud_media_backup(
      List<CloudMediaBackup> self, SseSerializer serializer);

  @protected
  void sse_encode_list_conversation(
      List<Conversation> self, SseSerializer serializer);

  @protected
  void sse_encode_list_event(List<Event> self, SseSerializer serializer);

  @protected
  void sse_encode_list_llm_profile(
      List<LlmProfile> self, SseSerializer serializer);

  @protected
  void sse_encode_list_llm_usage_aggregate(
      List<LlmUsageAggregate> self, SseSerializer serializer);

  @protected
  void sse_encode_list_message(List<Message> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_similar_message(
      List<SimilarMessage> self, SseSerializer serializer);

  @protected
  void sse_encode_list_similar_todo_thread(
      List<SimilarTodoThread> self, SseSerializer serializer);

  @protected
  void sse_encode_list_todo(List<Todo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_todo_activity(
      List<TodoActivity> self, SseSerializer serializer);

  @protected
  void sse_encode_llm_profile(LlmProfile self, SseSerializer serializer);

  @protected
  void sse_encode_llm_usage_aggregate(
      LlmUsageAggregate self, SseSerializer serializer);

  @protected
  void sse_encode_message(Message self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_similar_message(
      SimilarMessage self, SseSerializer serializer);

  @protected
  void sse_encode_similar_todo_thread(
      SimilarTodoThread self, SseSerializer serializer);

  @protected
  void sse_encode_todo(Todo self, SseSerializer serializer);

  @protected
  void sse_encode_todo_activity(TodoActivity self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
