// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TodoCandidate {
  final String id;
  final String title;
  final String status;
  final String? dueLocalIso;

  const TodoCandidate({
    required this.id,
    required this.title,
    required this.status,
    this.dueLocalIso,
  });

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ status.hashCode ^ dueLocalIso.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoCandidate &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          status == other.status &&
          dueLocalIso == other.dueLocalIso;
}
