// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class OcrPayload {
  final String ocrTextFull;
  final String ocrTextExcerpt;
  final String ocrEngine;
  final bool ocrIsTruncated;
  final int ocrPageCount;
  final int ocrProcessedPages;

  const OcrPayload({
    required this.ocrTextFull,
    required this.ocrTextExcerpt,
    required this.ocrEngine,
    required this.ocrIsTruncated,
    required this.ocrPageCount,
    required this.ocrProcessedPages,
  });

  @override
  int get hashCode =>
      ocrTextFull.hashCode ^
      ocrTextExcerpt.hashCode ^
      ocrEngine.hashCode ^
      ocrIsTruncated.hashCode ^
      ocrPageCount.hashCode ^
      ocrProcessedPages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OcrPayload &&
          runtimeType == other.runtimeType &&
          ocrTextFull == other.ocrTextFull &&
          ocrTextExcerpt == other.ocrTextExcerpt &&
          ocrEngine == other.ocrEngine &&
          ocrIsTruncated == other.ocrIsTruncated &&
          ocrPageCount == other.ocrPageCount &&
          ocrProcessedPages == other.ocrProcessedPages;
}
