// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_scoped_empty_answer`, `build_scoped_prompt`, `collect_scoped_contexts`, `emit_ask_ai_meta_if_any`, `emit_scoped_empty_answer`, `finish_ask_ai_stream`, `key_from_bytes`, `list_all_message_ids`, `list_conversation_message_ids`, `list_message_ids_by_tag_scope`, `normalize_tag_ids`, `normalize_topic_thread_id`, `stream_scoped_ask_with_provider`
// These types are ignored because they are not used by any `pub` functions: `ScopedFocus`, `TimeScope`

Stream<String> ragAskAiStreamScoped(
        {required String appDir,
        required List<int> key,
        required String conversationId,
        required String question,
        required int topK,
        required bool thisThreadOnly,
        PlatformInt64? timeStartMs,
        PlatformInt64? timeEndMs,
        required List<String> includeTagIds,
        required List<String> excludeTagIds,
        String? topicThreadId,
        required bool strictMode,
        required String localeLanguage,
        required String localDay}) =>
    RustLib.instance.api.crateApiAskScopeRagAskAiStreamScoped(
        appDir: appDir,
        key: key,
        conversationId: conversationId,
        question: question,
        topK: topK,
        thisThreadOnly: thisThreadOnly,
        timeStartMs: timeStartMs,
        timeEndMs: timeEndMs,
        includeTagIds: includeTagIds,
        excludeTagIds: excludeTagIds,
        topicThreadId: topicThreadId,
        strictMode: strictMode,
        localeLanguage: localeLanguage,
        localDay: localDay);

Stream<String> ragAskAiStreamCloudGatewayScoped(
        {required String appDir,
        required List<int> key,
        required String conversationId,
        required String question,
        required int topK,
        required bool thisThreadOnly,
        PlatformInt64? timeStartMs,
        PlatformInt64? timeEndMs,
        required List<String> includeTagIds,
        required List<String> excludeTagIds,
        String? topicThreadId,
        required bool strictMode,
        required String localeLanguage,
        required String gatewayBaseUrl,
        required String firebaseIdToken,
        required String modelName}) =>
    RustLib.instance.api.crateApiAskScopeRagAskAiStreamCloudGatewayScoped(
        appDir: appDir,
        key: key,
        conversationId: conversationId,
        question: question,
        topK: topK,
        thisThreadOnly: thisThreadOnly,
        timeStartMs: timeStartMs,
        timeEndMs: timeEndMs,
        includeTagIds: includeTagIds,
        excludeTagIds: excludeTagIds,
        topicThreadId: topicThreadId,
        strictMode: strictMode,
        localeLanguage: localeLanguage,
        gatewayBaseUrl: gatewayBaseUrl,
        firebaseIdToken: firebaseIdToken,
        modelName: modelName);
