// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../db.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key_from_bytes`

Future<AttachmentMetadata?> dbReadAttachmentMetadata(
        {required String appDir,
        required List<int> key,
        required String attachmentSha256}) =>
    RustLib.instance.api.crateApiAttachmentsDbReadAttachmentMetadata(
        appDir: appDir, key: key, attachmentSha256: attachmentSha256);

Future<void> dbUpsertAttachmentMetadata(
        {required String appDir,
        required List<int> key,
        required String attachmentSha256,
        String? title,
        required List<String> filenames,
        required List<String> sourceUrls}) =>
    RustLib.instance.api.crateApiAttachmentsDbUpsertAttachmentMetadata(
        appDir: appDir,
        key: key,
        attachmentSha256: attachmentSha256,
        title: title,
        filenames: filenames,
        sourceUrls: sourceUrls);
