// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `audio_input_format_by_mime_type`, `chat_message_content_to_text`, `decode_local_whisper_wav_bytes`, `extract_chat_stream_delta_text`, `extract_text_from_json_value`, `extract_transcript_text`, `file_ext_for_mime_type`, `is_auto_transcribe_lang`, `key_from_bytes`, `local_whisper_model_filename`, `multimodal_transcribe_prompt`, `normalize_local_whisper_lang`, `normalize_local_whisper_model_name`, `normalize_transcript_text`, `openai_audio_transcriptions_url`, `openai_chat_completions_url`, `parse_chat_transcribe_sse_payload`, `parse_sse_data_events`, `parse_usage_value`, `parse_whisper_sse_payload`, `resolve_local_whisper_model_path`
// These types are ignored because they are not used by any `pub` functions: `OpenAiAudioTranscribeResponse`, `OpenAiUsage`

Future<String> audioTranscribeLocalWhisper(
        {required String appDir,
        required String modelName,
        required String lang,
        required List<int> wavBytes}) =>
    RustLib.instance.api.crateApiAudioTranscribeAudioTranscribeLocalWhisper(
        appDir: appDir, modelName: modelName, lang: lang, wavBytes: wavBytes);

Future<String> audioTranscribeByokProfile(
        {required String appDir,
        required List<int> key,
        required String profileId,
        required String localDay,
        required String lang,
        required String mimeType,
        required List<int> audioBytes}) =>
    RustLib.instance.api.crateApiAudioTranscribeAudioTranscribeByokProfile(
        appDir: appDir,
        key: key,
        profileId: profileId,
        localDay: localDay,
        lang: lang,
        mimeType: mimeType,
        audioBytes: audioBytes);

Future<String> audioTranscribeByokProfileMultimodal(
        {required String appDir,
        required List<int> key,
        required String profileId,
        required String localDay,
        required String lang,
        required String mimeType,
        required List<int> audioBytes}) =>
    RustLib.instance.api
        .crateApiAudioTranscribeAudioTranscribeByokProfileMultimodal(
            appDir: appDir,
            key: key,
            profileId: profileId,
            localDay: localDay,
            lang: lang,
            mimeType: mimeType,
            audioBytes: audioBytes);
