// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../db.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key_from_bytes`

Future<List<AttachmentAnnotationJob>> dbListDueImageAttachmentAnnotations(
        {required String appDir,
        required List<int> key,
        required PlatformInt64 nowMs,
        required int limit}) =>
    RustLib.instance.api
        .crateApiContentExtractDbListDueImageAttachmentAnnotations(
            appDir: appDir, key: key, nowMs: nowMs, limit: limit);

Future<List<AttachmentAnnotationJob>> dbListDueUrlManifestAttachmentAnnotations(
        {required String appDir,
        required List<int> key,
        required PlatformInt64 nowMs,
        required int limit}) =>
    RustLib.instance.api
        .crateApiContentExtractDbListDueUrlManifestAttachmentAnnotations(
            appDir: appDir, key: key, nowMs: nowMs, limit: limit);

Future<int> dbProcessPendingDocumentExtractions(
        {required String appDir, required List<int> key, required int limit}) =>
    RustLib.instance.api
        .crateApiContentExtractDbProcessPendingDocumentExtractions(
            appDir: appDir, key: key, limit: limit);

Future<String?> dbReadAttachmentAnnotationPayloadJson(
        {required String appDir,
        required List<int> key,
        required String attachmentSha256}) =>
    RustLib.instance.api
        .crateApiContentExtractDbReadAttachmentAnnotationPayloadJson(
            appDir: appDir, key: key, attachmentSha256: attachmentSha256);
