// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../db.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key_from_bytes`

Future<ContentEnrichmentConfig> dbGetContentEnrichmentConfig(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api.crateApiContentEnrichmentDbGetContentEnrichmentConfig(
        appDir: appDir, key: key);

Future<void> dbSetContentEnrichmentConfig(
        {required String appDir,
        required List<int> key,
        required ContentEnrichmentConfig config}) =>
    RustLib.instance.api.crateApiContentEnrichmentDbSetContentEnrichmentConfig(
        appDir: appDir, key: key, config: config);

Future<StoragePolicyConfig> dbGetStoragePolicyConfig(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api.crateApiContentEnrichmentDbGetStoragePolicyConfig(
        appDir: appDir, key: key);

Future<void> dbSetStoragePolicyConfig(
        {required String appDir,
        required List<int> key,
        required StoragePolicyConfig config}) =>
    RustLib.instance.api.crateApiContentEnrichmentDbSetStoragePolicyConfig(
        appDir: appDir, key: key, config: config);
