// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../db.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key_from_bytes`

Future<bool> authIsInitialized({required String appDir}) =>
    RustLib.instance.api.crateApiCoreAuthIsInitialized(appDir: appDir);

Future<Uint8List> authInitMasterPassword(
        {required String appDir, required String password}) =>
    RustLib.instance.api
        .crateApiCoreAuthInitMasterPassword(appDir: appDir, password: password);

Future<Uint8List> authUnlockWithPassword(
        {required String appDir, required String password}) =>
    RustLib.instance.api
        .crateApiCoreAuthUnlockWithPassword(appDir: appDir, password: password);

Future<void> authValidateKey(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api.crateApiCoreAuthValidateKey(appDir: appDir, key: key);

Future<List<Conversation>> dbListConversations(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api
        .crateApiCoreDbListConversations(appDir: appDir, key: key);

Future<Conversation> dbCreateConversation(
        {required String appDir,
        required List<int> key,
        required String title}) =>
    RustLib.instance.api.crateApiCoreDbCreateConversation(
        appDir: appDir, key: key, title: title);

Future<List<Message>> dbListMessages(
        {required String appDir,
        required List<int> key,
        required String conversationId}) =>
    RustLib.instance.api.crateApiCoreDbListMessages(
        appDir: appDir, key: key, conversationId: conversationId);

Future<Message> dbInsertMessage(
        {required String appDir,
        required List<int> key,
        required String conversationId,
        required String role,
        required String content}) =>
    RustLib.instance.api.crateApiCoreDbInsertMessage(
        appDir: appDir,
        key: key,
        conversationId: conversationId,
        role: role,
        content: content);

Future<int> dbProcessPendingMessageEmbeddings(
        {required String appDir, required List<int> key, required int limit}) =>
    RustLib.instance.api.crateApiCoreDbProcessPendingMessageEmbeddings(
        appDir: appDir, key: key, limit: limit);

Future<List<SimilarMessage>> dbSearchSimilarMessages(
        {required String appDir,
        required List<int> key,
        required String query,
        required int topK}) =>
    RustLib.instance.api.crateApiCoreDbSearchSimilarMessages(
        appDir: appDir, key: key, query: query, topK: topK);

Future<int> dbRebuildMessageEmbeddings(
        {required String appDir,
        required List<int> key,
        required int batchLimit}) =>
    RustLib.instance.api.crateApiCoreDbRebuildMessageEmbeddings(
        appDir: appDir, key: key, batchLimit: batchLimit);
