// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key_from_bytes`

Future<bool> dbApplyDetachedAskCompletionOnce(
        {required String appDir,
        required List<int> key,
        required String requestId,
        required String conversationId,
        required String question,
        required String answer}) =>
    RustLib.instance.api.crateApiDetachedAskDbApplyDetachedAskCompletionOnce(
        appDir: appDir,
        key: key,
        requestId: requestId,
        conversationId: conversationId,
        question: question,
        answer: answer);
