// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key_from_bytes`

Future<bool> dbReleaseLocalEmbeddingModelIfIdle(
        {required String appDir,
        required List<int> key,
        required int maxIdleMs}) =>
    RustLib.instance.api
        .crateApiEmbeddingLifecycleDbReleaseLocalEmbeddingModelIfIdle(
            appDir: appDir, key: key, maxIdleMs: maxIdleMs);
