// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../db.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `emit_progress`, `emit_result`, `key_from_bytes`

Future<ExternalImportScanSummary> externalImportScanSource(
        {required String appDir, required String sourcePath}) =>
    RustLib.instance.api.crateApiExternalImportExternalImportScanSource(
        appDir: appDir, sourcePath: sourcePath);

Future<List<ExternalImportBatchSummary>> externalImportListBatches(
        {required String appDir}) =>
    RustLib.instance.api
        .crateApiExternalImportExternalImportListBatches(appDir: appDir);

Future<String> externalImportBatchReportJson(
        {required String appDir, required String batchId}) =>
    RustLib.instance.api.crateApiExternalImportExternalImportBatchReportJson(
        appDir: appDir, batchId: batchId);

Future<void> externalImportDeleteBatch(
        {required String appDir, required String batchId}) =>
    RustLib.instance.api.crateApiExternalImportExternalImportDeleteBatch(
        appDir: appDir, batchId: batchId);

Future<void> externalImportRequestCancel(
        {required String appDir, required String batchId}) =>
    RustLib.instance.api.crateApiExternalImportExternalImportRequestCancel(
        appDir: appDir, batchId: batchId);

Future<String> externalImportPhaseBEstimateJson(
        {required String appDir, required String batchId}) =>
    RustLib.instance.api.crateApiExternalImportExternalImportPhaseBEstimateJson(
        appDir: appDir, batchId: batchId);

Future<String> externalImportPhaseBStateJson(
        {required String appDir, required String batchId}) =>
    RustLib.instance.api.crateApiExternalImportExternalImportPhaseBStateJson(
        appDir: appDir, batchId: batchId);

Stream<String> externalImportRunProgress(
        {required String appDir,
        required List<int> key,
        required String sourcePath}) =>
    RustLib.instance.api.crateApiExternalImportExternalImportRunProgress(
        appDir: appDir, key: key, sourcePath: sourcePath);

Stream<String> externalImportPhaseBRunProgress(
        {required String appDir,
        required List<int> key,
        required String batchId}) =>
    RustLib.instance.api.crateApiExternalImportExternalImportPhaseBRunProgress(
        appDir: appDir, key: key, batchId: batchId);
