// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../knowledge/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key_from_bytes`, `read_knowledge_debug_stats`

Future<KnowledgeIndexStatus> dbGetKnowledgeIndexStatus(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api
        .crateApiKnowledgeDbGetKnowledgeIndexStatus(appDir: appDir, key: key);

Future<void> dbRequestKnowledgeRebuild(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api
        .crateApiKnowledgeDbRequestKnowledgeRebuild(appDir: appDir, key: key);

Future<int> dbProcessPendingKnowledgeIndexJobs(
        {required String appDir, required List<int> key, required int limit}) =>
    RustLib.instance.api.crateApiKnowledgeDbProcessPendingKnowledgeIndexJobs(
        appDir: appDir, key: key, limit: limit);

Future<void> dbCancelKnowledgeRebuild(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api
        .crateApiKnowledgeDbCancelKnowledgeRebuild(appDir: appDir, key: key);

Future<KnowledgeDebugStats> dbGetKnowledgeDebugStats(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api
        .crateApiKnowledgeDbGetKnowledgeDebugStats(appDir: appDir, key: key);

Future<List<ContentKnowledgeDocument>> dbListKnowledgeDocuments(
        {required String appDir,
        required List<int> key,
        required int limit,
        required int offset}) =>
    RustLib.instance.api.crateApiKnowledgeDbListKnowledgeDocuments(
        appDir: appDir, key: key, limit: limit, offset: offset);

Future<KnowledgeMemoryFeedback> dbUpsertKnowledgeMemoryFeedback(
        {required String appDir,
        required List<int> key,
        required String documentId,
        KnowledgeMemoryStatus? status,
        required bool useForAskAi,
        required bool isDeleted,
        required bool markedInaccurate,
        String? correctedTitle,
        String? correctedSummary}) =>
    RustLib.instance.api.crateApiKnowledgeDbUpsertKnowledgeMemoryFeedback(
        appDir: appDir,
        key: key,
        documentId: documentId,
        status: status,
        useForAskAi: useForAskAi,
        isDeleted: isDeleted,
        markedInaccurate: markedInaccurate,
        correctedTitle: correctedTitle,
        correctedSummary: correctedSummary);

Future<List<KnowledgeUnit>> dbListKnowledgeUnits(
        {required String appDir,
        required List<int> key,
        required String documentId,
        KnowledgeUnitKind? unitKind,
        required int limit,
        required int offset}) =>
    RustLib.instance.api.crateApiKnowledgeDbListKnowledgeUnits(
        appDir: appDir,
        key: key,
        documentId: documentId,
        unitKind: unitKind,
        limit: limit,
        offset: offset);

Future<List<KnowledgeSearchResult>> dbSearchKnowledge(
        {required String appDir,
        required List<int> key,
        required String query,
        String? conversationId,
        String? documentId,
        required int limit}) =>
    RustLib.instance.api.crateApiKnowledgeDbSearchKnowledge(
        appDir: appDir,
        key: key,
        query: query,
        conversationId: conversationId,
        documentId: documentId,
        limit: limit);

Future<KnowledgeViewerDocument> dbGetKnowledgeDocument(
        {required String appDir,
        required List<int> key,
        required String documentId}) =>
    RustLib.instance.api.crateApiKnowledgeDbGetKnowledgeDocument(
        appDir: appDir, key: key, documentId: documentId);

Future<KnowledgeViewerPage> dbListKnowledgeViewerUnits(
        {required String appDir,
        required List<int> key,
        required String documentId,
        KnowledgeUnitKind? unitKind,
        required int limit,
        required int offset}) =>
    RustLib.instance.api.crateApiKnowledgeDbListKnowledgeViewerUnits(
        appDir: appDir,
        key: key,
        documentId: documentId,
        unitKind: unitKind,
        limit: limit,
        offset: offset);

Future<List<KnowledgeSearchResult>> dbSearchKnowledgeDocumentUnits(
        {required String appDir,
        required List<int> key,
        required String documentId,
        required String query,
        required int limit}) =>
    RustLib.instance.api.crateApiKnowledgeDbSearchKnowledgeDocumentUnits(
        appDir: appDir,
        key: key,
        documentId: documentId,
        query: query,
        limit: limit);

Future<List<KnowledgeUnit>> dbListKnowledgeUnitsAroundAnchor(
        {required String appDir,
        required List<int> key,
        required String documentId,
        required KnowledgeAnchorSet anchor,
        required int before,
        required int after}) =>
    RustLib.instance.api.crateApiKnowledgeDbListKnowledgeUnitsAroundAnchor(
        appDir: appDir,
        key: key,
        documentId: documentId,
        anchor: anchor,
        before: before,
        after: after);
