// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../knowledge/history.dart';
import '../knowledge/lint.dart';
import '../knowledge/models.dart';
import '../knowledge/pages.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key_from_bytes`, `read_knowledge_debug_stats`

Future<KnowledgeIndexStatus> dbGetKnowledgeIndexStatus(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api
        .crateApiKnowledgeDbGetKnowledgeIndexStatus(appDir: appDir, key: key);

Future<void> dbRequestKnowledgeRebuild(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api
        .crateApiKnowledgeDbRequestKnowledgeRebuild(appDir: appDir, key: key);

Future<int> dbProcessPendingKnowledgeIndexJobs(
        {required String appDir, required List<int> key, required int limit}) =>
    RustLib.instance.api.crateApiKnowledgeDbProcessPendingKnowledgeIndexJobs(
        appDir: appDir, key: key, limit: limit);

Future<void> dbCancelKnowledgeRebuild(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api
        .crateApiKnowledgeDbCancelKnowledgeRebuild(appDir: appDir, key: key);

Future<KnowledgeDebugStats> dbGetKnowledgeDebugStats(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api
        .crateApiKnowledgeDbGetKnowledgeDebugStats(appDir: appDir, key: key);

Future<List<ContentKnowledgeDocument>> dbListKnowledgeDocuments(
        {required String appDir,
        required List<int> key,
        required int limit,
        required int offset}) =>
    RustLib.instance.api.crateApiKnowledgeDbListKnowledgeDocuments(
        appDir: appDir, key: key, limit: limit, offset: offset);

Future<List<ContentKnowledgeDocument>> dbListGeneratedMemoryDocuments(
        {required String appDir,
        required List<int> key,
        required int limit,
        required int offset}) =>
    RustLib.instance.api.crateApiKnowledgeDbListGeneratedMemoryDocuments(
        appDir: appDir, key: key, limit: limit, offset: offset);

Future<List<KnowledgePageSummary>> dbListKnowledgePageSummaries(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api.crateApiKnowledgeDbListKnowledgePageSummaries(
        appDir: appDir, key: key);

Future<List<KnowledgePageChangeRecord>> dbListRecentKnowledgePageChanges(
        {required String appDir, required List<int> key, required int limit}) =>
    RustLib.instance.api.crateApiKnowledgeDbListRecentKnowledgePageChanges(
        appDir: appDir, key: key, limit: limit);

Future<KnowledgePageDetail> dbGetKnowledgePageDetail(
        {required String appDir,
        required List<int> key,
        required String pageId}) =>
    RustLib.instance.api.crateApiKnowledgeDbGetKnowledgePageDetail(
        appDir: appDir, key: key, pageId: pageId);

Future<KnowledgePageDetail> dbCorrectKnowledgePage(
        {required String appDir,
        required List<int> key,
        required String pageId,
        String? title,
        String? summary,
        String? body}) =>
    RustLib.instance.api.crateApiKnowledgeDbCorrectKnowledgePage(
        appDir: appDir,
        key: key,
        pageId: pageId,
        title: title,
        summary: summary,
        body: body);

Future<KnowledgePageDetail> dbMarkKnowledgePageWrong(
        {required String appDir,
        required List<int> key,
        required String pageId,
        required KnowledgeWrongReason reason,
        String? note}) =>
    RustLib.instance.api.crateApiKnowledgeDbMarkKnowledgePageWrong(
        appDir: appDir, key: key, pageId: pageId, reason: reason, note: note);

Future<KnowledgePageDetail> dbSetKnowledgePageAnswerAllowed(
        {required String appDir,
        required List<int> key,
        required String pageId,
        required bool allowed,
        String? note}) =>
    RustLib.instance.api.crateApiKnowledgeDbSetKnowledgePageAnswerAllowed(
        appDir: appDir, key: key, pageId: pageId, allowed: allowed, note: note);

Future<KnowledgePageDetail> dbArchiveKnowledgePage(
        {required String appDir,
        required List<int> key,
        required String pageId,
        String? note}) =>
    RustLib.instance.api.crateApiKnowledgeDbArchiveKnowledgePage(
        appDir: appDir, key: key, pageId: pageId, note: note);

Future<KnowledgePageDetail> dbRemoveKnowledgePage(
        {required String appDir,
        required List<int> key,
        required String pageId,
        String? note}) =>
    RustLib.instance.api.crateApiKnowledgeDbRemoveKnowledgePage(
        appDir: appDir, key: key, pageId: pageId, note: note);

Future<KnowledgePageDetail> dbMergeKnowledgePageInto(
        {required String appDir,
        required List<int> key,
        required String pageId,
        required String targetPageId,
        String? note}) =>
    RustLib.instance.api.crateApiKnowledgeDbMergeKnowledgePageInto(
        appDir: appDir,
        key: key,
        pageId: pageId,
        targetPageId: targetPageId,
        note: note);

Future<KnowledgeMemoryFeedback> dbUpsertKnowledgeMemoryFeedback(
        {required String appDir,
        required List<int> key,
        required String documentId,
        KnowledgeMemoryStatus? status,
        required bool useForAskAi,
        required bool isDeleted,
        required bool markedInaccurate,
        String? correctedTitle,
        String? correctedSummary}) =>
    RustLib.instance.api.crateApiKnowledgeDbUpsertKnowledgeMemoryFeedback(
        appDir: appDir,
        key: key,
        documentId: documentId,
        status: status,
        useForAskAi: useForAskAi,
        isDeleted: isDeleted,
        markedInaccurate: markedInaccurate,
        correctedTitle: correctedTitle,
        correctedSummary: correctedSummary);

Future<List<KnowledgeUnit>> dbListKnowledgeUnits(
        {required String appDir,
        required List<int> key,
        required String documentId,
        KnowledgeUnitKind? unitKind,
        required int limit,
        required int offset}) =>
    RustLib.instance.api.crateApiKnowledgeDbListKnowledgeUnits(
        appDir: appDir,
        key: key,
        documentId: documentId,
        unitKind: unitKind,
        limit: limit,
        offset: offset);

Future<List<KnowledgeSearchResult>> dbSearchKnowledge(
        {required String appDir,
        required List<int> key,
        required String query,
        String? conversationId,
        String? documentId,
        required int limit}) =>
    RustLib.instance.api.crateApiKnowledgeDbSearchKnowledge(
        appDir: appDir,
        key: key,
        query: query,
        conversationId: conversationId,
        documentId: documentId,
        limit: limit);

Future<KnowledgeViewerDocument> dbGetKnowledgeDocument(
        {required String appDir,
        required List<int> key,
        required String documentId}) =>
    RustLib.instance.api.crateApiKnowledgeDbGetKnowledgeDocument(
        appDir: appDir, key: key, documentId: documentId);

Future<KnowledgeViewerPage> dbListKnowledgeViewerUnits(
        {required String appDir,
        required List<int> key,
        required String documentId,
        KnowledgeUnitKind? unitKind,
        required int limit,
        required int offset}) =>
    RustLib.instance.api.crateApiKnowledgeDbListKnowledgeViewerUnits(
        appDir: appDir,
        key: key,
        documentId: documentId,
        unitKind: unitKind,
        limit: limit,
        offset: offset);

Future<List<KnowledgeUnit>> dbListRecentKnowledgeViewerUnits(
        {required String appDir,
        required List<int> key,
        required String documentId,
        KnowledgeUnitKind? unitKind,
        required int limit}) =>
    RustLib.instance.api.crateApiKnowledgeDbListRecentKnowledgeViewerUnits(
        appDir: appDir,
        key: key,
        documentId: documentId,
        unitKind: unitKind,
        limit: limit);

Future<List<KnowledgeSearchResult>> dbSearchKnowledgeDocumentUnits(
        {required String appDir,
        required List<int> key,
        required String documentId,
        required String query,
        required int limit}) =>
    RustLib.instance.api.crateApiKnowledgeDbSearchKnowledgeDocumentUnits(
        appDir: appDir,
        key: key,
        documentId: documentId,
        query: query,
        limit: limit);

Future<List<KnowledgeUnit>> dbListKnowledgeUnitsAroundAnchor(
        {required String appDir,
        required List<int> key,
        required String documentId,
        required KnowledgeAnchorSet anchor,
        required int before,
        required int after}) =>
    RustLib.instance.api.crateApiKnowledgeDbListKnowledgeUnitsAroundAnchor(
        appDir: appDir,
        key: key,
        documentId: documentId,
        anchor: anchor,
        before: before,
        after: after);
