// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../knowledge/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key_from_bytes`

Future<KnowledgeIndexStatus> dbGetKnowledgeIndexStatus(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api
        .crateApiKnowledgeDbGetKnowledgeIndexStatus(appDir: appDir, key: key);

Future<void> dbRequestKnowledgeRebuild(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api
        .crateApiKnowledgeDbRequestKnowledgeRebuild(appDir: appDir, key: key);

Future<int> dbProcessPendingKnowledgeIndexJobs(
        {required String appDir, required List<int> key, required int limit}) =>
    RustLib.instance.api.crateApiKnowledgeDbProcessPendingKnowledgeIndexJobs(
        appDir: appDir, key: key, limit: limit);

Future<void> dbCancelKnowledgeRebuild(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api
        .crateApiKnowledgeDbCancelKnowledgeRebuild(appDir: appDir, key: key);

Future<List<ContentKnowledgeDocument>> dbListKnowledgeDocuments(
        {required String appDir,
        required List<int> key,
        required int limit,
        required int offset}) =>
    RustLib.instance.api.crateApiKnowledgeDbListKnowledgeDocuments(
        appDir: appDir, key: key, limit: limit, offset: offset);

Future<List<KnowledgeUnit>> dbListKnowledgeUnits(
        {required String appDir,
        required List<int> key,
        required String documentId,
        KnowledgeUnitKind? unitKind,
        required int limit,
        required int offset}) =>
    RustLib.instance.api.crateApiKnowledgeDbListKnowledgeUnits(
        appDir: appDir,
        key: key,
        documentId: documentId,
        unitKind: unitKind,
        limit: limit,
        offset: offset);
