// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../db.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key_from_bytes`

Future<MediaAnnotationConfig> dbGetMediaAnnotationConfig(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api.crateApiMediaAnnotationDbGetMediaAnnotationConfig(
        appDir: appDir, key: key);

Future<void> dbSetMediaAnnotationConfig(
        {required String appDir,
        required List<int> key,
        required MediaAnnotationConfig config}) =>
    RustLib.instance.api.crateApiMediaAnnotationDbSetMediaAnnotationConfig(
        appDir: appDir, key: key, config: config);

Future<String> mediaAnnotationByokProfile(
        {required String appDir,
        required List<int> key,
        required String profileId,
        required String localDay,
        required String lang,
        required String mimeType,
        required List<int> imageBytes}) =>
    RustLib.instance.api.crateApiMediaAnnotationMediaAnnotationByokProfile(
        appDir: appDir,
        key: key,
        profileId: profileId,
        localDay: localDay,
        lang: lang,
        mimeType: mimeType,
        imageBytes: imageBytes);
