// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../db.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `emit_progress`, `emit_result`, `key_from_bytes`, `validate_inactive_rollback_snapshot_restore_access`

Future<MigrationArchiveManifest> migrationArchiveParseManifestJson(
        {required String manifestJson}) =>
    RustLib.instance.api
        .crateApiMigrationArchiveMigrationArchiveParseManifestJson(
            manifestJson: manifestJson);

Future<String> migrationArchiveMarkdownPathForItemId(
        {required String itemId}) =>
    RustLib.instance.api
        .crateApiMigrationArchiveMigrationArchiveMarkdownPathForItemId(
            itemId: itemId);

Future<String> migrationArchiveWikilinkForItem(
        {required String itemId, required String title}) =>
    RustLib.instance.api
        .crateApiMigrationArchiveMigrationArchiveWikilinkForItem(
            itemId: itemId, title: title);

Future<MigrationArchiveExportEstimate> migrationArchiveExportEstimate(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api.crateApiMigrationArchiveMigrationArchiveExportEstimate(
        appDir: appDir, key: key);

Future<MigrationArchiveManifest> migrationArchiveExport(
        {required String appDir,
        required List<int> key,
        required String outputPath}) =>
    RustLib.instance.api.crateApiMigrationArchiveMigrationArchiveExport(
        appDir: appDir, key: key, outputPath: outputPath);

Stream<String> migrationArchiveExportProgress(
        {required String appDir,
        required List<int> key,
        required String outputPath}) =>
    RustLib.instance.api.crateApiMigrationArchiveMigrationArchiveExportProgress(
        appDir: appDir, key: key, outputPath: outputPath);

Future<MigrationArchiveManifest> migrationArchiveImport(
        {required String appDir,
        required List<int> key,
        required String archivePath}) =>
    RustLib.instance.api.crateApiMigrationArchiveMigrationArchiveImport(
        appDir: appDir, key: key, archivePath: archivePath);

Future<String?> migrationArchiveCreateRollbackSnapshot(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api
        .crateApiMigrationArchiveMigrationArchiveCreateRollbackSnapshot(
            appDir: appDir, key: key);

Future<void> migrationArchiveRestoreRollbackSnapshot(
        {required String appDir,
        required List<int> key,
        required String snapshotPath}) =>
    RustLib.instance.api
        .crateApiMigrationArchiveMigrationArchiveRestoreRollbackSnapshot(
            appDir: appDir, key: key, snapshotPath: snapshotPath);

Future<void> migrationArchiveRemoveRollbackSnapshot(
        {required String snapshotPath}) =>
    RustLib.instance.api
        .crateApiMigrationArchiveMigrationArchiveRemoveRollbackSnapshot(
            snapshotPath: snapshotPath);

Stream<String> migrationArchiveImportProgress(
        {required String appDir,
        required List<int> key,
        required String archivePath}) =>
    RustLib.instance.api.crateApiMigrationArchiveMigrationArchiveImportProgress(
        appDir: appDir, key: key, archivePath: archivePath);

Future<MigrationArchiveManifest> migrationArchiveInspect(
        {required String appDir, required String archivePath}) =>
    RustLib.instance.api.crateApiMigrationArchiveMigrationArchiveInspect(
        appDir: appDir, archivePath: archivePath);
