// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `into_db_backend`, `key_from_bytes`

Future<OplogMaintenanceStats> dbRunOplogMaintenance(
        {required String appDir,
        required List<int> key,
        required OplogMaintenanceBackend backend,
        required String scopeId}) =>
    RustLib.instance.api.crateApiOplogMaintenanceDbRunOplogMaintenance(
        appDir: appDir, key: key, backend: backend, scopeId: scopeId);

enum OplogMaintenanceBackend {
  webDav,
  localDir,
  managedVault,
  ;
}

class OplogMaintenanceStats {
  final BigInt beforeCount;
  final BigInt afterCount;
  final BigInt prunedCount;

  const OplogMaintenanceStats({
    required this.beforeCount,
    required this.afterCount,
    required this.prunedCount,
  });

  @override
  int get hashCode =>
      beforeCount.hashCode ^ afterCount.hashCode ^ prunedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OplogMaintenanceStats &&
          runtimeType == other.runtimeType &&
          beforeCount == other.beforeCount &&
          afterCount == other.afterCount &&
          prunedCount == other.prunedCount;
}
