// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../semantic_parse.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key_from_bytes`

Future<String> aiSemanticParseMessageActionEnhancement(
        {required String appDir,
        required List<int> key,
        required String text,
        required String nowLocalIso,
        required String locale,
        required int dayEndMinutes,
        required String localResultJson,
        required List<String> unresolvedFields,
        required List<TodoCandidate> candidates,
        required String localDay}) =>
    RustLib.instance.api
        .crateApiSemanticParseEnhancementAiSemanticParseMessageActionEnhancement(
            appDir: appDir,
            key: key,
            text: text,
            nowLocalIso: nowLocalIso,
            locale: locale,
            dayEndMinutes: dayEndMinutes,
            localResultJson: localResultJson,
            unresolvedFields: unresolvedFields,
            candidates: candidates,
            localDay: localDay);

Future<String> aiSemanticParseMessageActionEnhancementCloudGateway(
        {required String appDir,
        required List<int> key,
        required String text,
        required String nowLocalIso,
        required String locale,
        required int dayEndMinutes,
        required String localResultJson,
        required List<String> unresolvedFields,
        required List<TodoCandidate> candidates,
        required String gatewayBaseUrl,
        required String firebaseIdToken,
        required String modelName}) =>
    RustLib.instance.api
        .crateApiSemanticParseEnhancementAiSemanticParseMessageActionEnhancementCloudGateway(
            appDir: appDir,
            key: key,
            text: text,
            nowLocalIso: nowLocalIso,
            locale: locale,
            dayEndMinutes: dayEndMinutes,
            localResultJson: localResultJson,
            unresolvedFields: unresolvedFields,
            candidates: candidates,
            gatewayBaseUrl: gatewayBaseUrl,
            firebaseIdToken: firebaseIdToken,
            modelName: modelName);
