// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key_from_bytes`

Future<bool> dbCompleteSemanticParseFollowupIfCurrentAttempt(
        {required String appDir,
        required List<int> key,
        required String messageId,
        required PlatformInt64 expectedAttemptId,
        required String todoId,
        String? todoTitle,
        String? newStatus,
        PlatformInt64? dueAtMs,
        List<String>? pendingSuggestedTags,
        List<String>? autoApplySuggestedTags,
        double? suggestedTagConfidence,
        required PlatformInt64 nowMs}) =>
    RustLib.instance.api
        .crateApiSemanticParseJobsDbCompleteSemanticParseFollowupIfCurrentAttempt(
            appDir: appDir,
            key: key,
            messageId: messageId,
            expectedAttemptId: expectedAttemptId,
            todoId: todoId,
            todoTitle: todoTitle,
            newStatus: newStatus,
            dueAtMs: dueAtMs,
            pendingSuggestedTags: pendingSuggestedTags,
            autoApplySuggestedTags: autoApplySuggestedTags,
            suggestedTagConfidence: suggestedTagConfidence,
            nowMs: nowMs);
