// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `emit_progress`, `emit_result`, `key_from_bytes`, `sync_key_from_bytes`

Stream<String> syncWebdavPullProgress(
        {required String appDir,
        required List<int> key,
        required List<int> syncKey,
        required String baseUrl,
        String? username,
        String? password,
        required String remoteRoot}) =>
    RustLib.instance.api.crateApiSyncProgressSyncWebdavPullProgress(
        appDir: appDir,
        key: key,
        syncKey: syncKey,
        baseUrl: baseUrl,
        username: username,
        password: password,
        remoteRoot: remoteRoot);

Stream<String> syncWebdavPushOpsOnlyProgress(
        {required String appDir,
        required List<int> key,
        required List<int> syncKey,
        required String baseUrl,
        String? username,
        String? password,
        required String remoteRoot}) =>
    RustLib.instance.api.crateApiSyncProgressSyncWebdavPushOpsOnlyProgress(
        appDir: appDir,
        key: key,
        syncKey: syncKey,
        baseUrl: baseUrl,
        username: username,
        password: password,
        remoteRoot: remoteRoot);

Stream<String> syncLocaldirPullProgress(
        {required String appDir,
        required List<int> key,
        required List<int> syncKey,
        required String localDir,
        required String remoteRoot}) =>
    RustLib.instance.api.crateApiSyncProgressSyncLocaldirPullProgress(
        appDir: appDir,
        key: key,
        syncKey: syncKey,
        localDir: localDir,
        remoteRoot: remoteRoot);

Stream<String> syncLocaldirPushProgress(
        {required String appDir,
        required List<int> key,
        required List<int> syncKey,
        required String localDir,
        required String remoteRoot}) =>
    RustLib.instance.api.crateApiSyncProgressSyncLocaldirPushProgress(
        appDir: appDir,
        key: key,
        syncKey: syncKey,
        localDir: localDir,
        remoteRoot: remoteRoot);

Stream<String> syncManagedVaultPullProgress(
        {required String appDir,
        required List<int> key,
        required List<int> syncKey,
        required String baseUrl,
        required String vaultId,
        required String idToken}) =>
    RustLib.instance.api.crateApiSyncProgressSyncManagedVaultPullProgress(
        appDir: appDir,
        key: key,
        syncKey: syncKey,
        baseUrl: baseUrl,
        vaultId: vaultId,
        idToken: idToken);

Stream<String> syncManagedVaultPushOpsOnlyProgress(
        {required String appDir,
        required List<int> key,
        required List<int> syncKey,
        required String baseUrl,
        required String vaultId,
        required String idToken}) =>
    RustLib.instance.api
        .crateApiSyncProgressSyncManagedVaultPushOpsOnlyProgress(
            appDir: appDir,
            key: key,
            syncKey: syncKey,
            baseUrl: baseUrl,
            vaultId: vaultId,
            idToken: idToken);
