// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_managed_vault_cursor_remote_diagnostics`, `client`, `json_value_to_i64`, `kv_get_i64`, `kv_scan_i64_map_by_prefix`, `kv_scan_keys_by_prefix`, `managed_vault_scope_id`, `parse_device_seq_map_from_payload`, `probe_remote_device_seq_map`, `read_local_device_id`, `url`
// These types are ignored because they are not used by any `pub` functions: `DiagnosticsRegisterDeviceRequest`, `DiagnosticsRegisterDeviceResponse`, `ManagedVaultCursorRemoteDiagnostics`, `PullProbeRequest`

Future<String> syncManagedVaultCursorDiagnostics(
        {required String appDir,
        required String baseUrl,
        required String vaultId,
        String? firebaseIdToken}) =>
    RustLib.instance.api
        .crateApiSyncDiagnosticsSyncManagedVaultCursorDiagnostics(
            appDir: appDir,
            baseUrl: baseUrl,
            vaultId: vaultId,
            firebaseIdToken: firebaseIdToken);
