// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../db.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key_from_bytes`

Future<List<Tag>> dbListTags(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api.crateApiTagsDbListTags(appDir: appDir, key: key);

Future<Tag> dbUpsertTag(
        {required String appDir,
        required List<int> key,
        required String name}) =>
    RustLib.instance.api
        .crateApiTagsDbUpsertTag(appDir: appDir, key: key, name: name);

Future<List<Tag>> dbListMessageTags(
        {required String appDir,
        required List<int> key,
        required String messageId}) =>
    RustLib.instance.api.crateApiTagsDbListMessageTags(
        appDir: appDir, key: key, messageId: messageId);

Future<List<Tag>> dbSetMessageTags(
        {required String appDir,
        required List<int> key,
        required String messageId,
        required List<String> tagIds}) =>
    RustLib.instance.api.crateApiTagsDbSetMessageTags(
        appDir: appDir, key: key, messageId: messageId, tagIds: tagIds);

Future<List<String>> dbListMessageSuggestedTags(
        {required String appDir,
        required List<int> key,
        required String messageId}) =>
    RustLib.instance.api.crateApiTagsDbListMessageSuggestedTags(
        appDir: appDir, key: key, messageId: messageId);

Future<List<TagMergeSuggestion>> dbListTagMergeSuggestions(
        {required String appDir, required List<int> key, required int limit}) =>
    RustLib.instance.api.crateApiTagsDbListTagMergeSuggestions(
        appDir: appDir, key: key, limit: limit);

Future<int> dbMergeTags(
        {required String appDir,
        required List<int> key,
        required String sourceTagId,
        required String targetTagId}) =>
    RustLib.instance.api.crateApiTagsDbMergeTags(
        appDir: appDir,
        key: key,
        sourceTagId: sourceTagId,
        targetTagId: targetTagId);

Future<void> dbRecordTagMergeFeedback(
        {required String appDir,
        required List<int> key,
        required String sourceTagId,
        required String targetTagId,
        required String reason,
        required String action}) =>
    RustLib.instance.api.crateApiTagsDbRecordTagMergeFeedback(
        appDir: appDir,
        key: key,
        sourceTagId: sourceTagId,
        targetTagId: targetTagId,
        reason: reason,
        action: action);

Future<List<String>> dbListMessageIdsByTagIds(
        {required String appDir,
        required List<int> key,
        required String conversationId,
        required List<String> tagIds}) =>
    RustLib.instance.api.crateApiTagsDbListMessageIdsByTagIds(
        appDir: appDir,
        key: key,
        conversationId: conversationId,
        tagIds: tagIds);
