// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../db.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `is_todo_access_error`, `key_from_bytes`, `list_visible_due_auto_todo_followup_generation_jobs`

Future<List<TodoFollowupGenerationJob>> dbListDueAutoTodoFollowupGenerationJobs(
        {required String appDir,
        required List<int> key,
        required PlatformInt64 nowMs,
        required int limit}) =>
    RustLib.instance.api
        .crateApiTodoFollowupGenerationDbListDueAutoTodoFollowupGenerationJobs(
            appDir: appDir, key: key, nowMs: nowMs, limit: limit);
