// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../db.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key_from_bytes`

Future<TopicThread> dbCreateTopicThread(
        {required String appDir,
        required List<int> key,
        required String conversationId,
        String? title}) =>
    RustLib.instance.api.crateApiTopicThreadsDbCreateTopicThread(
        appDir: appDir, key: key, conversationId: conversationId, title: title);

Future<List<TopicThread>> dbListTopicThreads(
        {required String appDir,
        required List<int> key,
        required String conversationId}) =>
    RustLib.instance.api.crateApiTopicThreadsDbListTopicThreads(
        appDir: appDir, key: key, conversationId: conversationId);

Future<TopicThread> dbUpdateTopicThreadTitle(
        {required String appDir,
        required List<int> key,
        required String threadId,
        String? title}) =>
    RustLib.instance.api.crateApiTopicThreadsDbUpdateTopicThreadTitle(
        appDir: appDir, key: key, threadId: threadId, title: title);

Future<bool> dbDeleteTopicThread(
        {required String appDir,
        required List<int> key,
        required String threadId}) =>
    RustLib.instance.api.crateApiTopicThreadsDbDeleteTopicThread(
        appDir: appDir, key: key, threadId: threadId);

Future<List<String>> dbSetTopicThreadMessageIds(
        {required String appDir,
        required List<int> key,
        required String threadId,
        required List<String> messageIds}) =>
    RustLib.instance.api.crateApiTopicThreadsDbSetTopicThreadMessageIds(
        appDir: appDir, key: key, threadId: threadId, messageIds: messageIds);

Future<List<String>> dbListTopicThreadMessageIds(
        {required String appDir,
        required List<int> key,
        required String threadId}) =>
    RustLib.instance.api.crateApiTopicThreadsDbListTopicThreadMessageIds(
        appDir: appDir, key: key, threadId: threadId);
