// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key_array`, `validate_inactive_rollback_snapshot_restore_access`

Future<String?> vaultRollbackCreateSnapshot(
        {required String appDir, required List<int> key}) =>
    RustLib.instance.api.crateApiVaultRollbackVaultRollbackCreateSnapshot(
        appDir: appDir, key: key);

Future<void> vaultRollbackRestoreSnapshot(
        {required String appDir,
        required List<int> key,
        required String snapshotPath}) =>
    RustLib.instance.api.crateApiVaultRollbackVaultRollbackRestoreSnapshot(
        appDir: appDir, key: key, snapshotPath: snapshotPath);

Future<void> vaultRollbackRemoveSnapshot({required String snapshotPath}) =>
    RustLib.instance.api.crateApiVaultRollbackVaultRollbackRemoveSnapshot(
        snapshotPath: snapshotPath);
