// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key_from_bytes`

Future<String> syncManagedVaultReadWebPullState(
        {required String appDir,
        required String baseUrl,
        required String vaultId}) =>
    RustLib.instance.api.crateApiWebSyncSyncManagedVaultReadWebPullState(
        appDir: appDir, baseUrl: baseUrl, vaultId: vaultId);

Future<String> syncManagedVaultApplyWebPullPage(
        {required String appDir,
        required List<int> key,
        required List<int> syncKey,
        required String baseUrl,
        required String vaultId,
        required String responseJson}) =>
    RustLib.instance.api.crateApiWebSyncSyncManagedVaultApplyWebPullPage(
        appDir: appDir,
        key: key,
        syncKey: syncKey,
        baseUrl: baseUrl,
        vaultId: vaultId,
        responseJson: responseJson);

Future<String> syncManagedVaultRecoverWebPullState(
        {required String appDir,
        required List<int> key,
        required String baseUrl,
        required String vaultId}) =>
    RustLib.instance.api.crateApiWebSyncSyncManagedVaultRecoverWebPullState(
        appDir: appDir, key: key, baseUrl: baseUrl, vaultId: vaultId);

Future<bool> syncManagedVaultFinalizeWebPull(
        {required String appDir,
        required List<int> key,
        required List<int> syncKey,
        required String baseUrl,
        required String vaultId,
        required String firebaseIdToken,
        required BigInt appliedOps}) =>
    RustLib.instance.api.crateApiWebSyncSyncManagedVaultFinalizeWebPull(
        appDir: appDir,
        key: key,
        syncKey: syncKey,
        baseUrl: baseUrl,
        vaultId: vaultId,
        firebaseIdToken: firebaseIdToken,
        appliedOps: appliedOps);

Future<String> syncManagedVaultPrepareWebPushBatch(
        {required String appDir,
        required List<int> key,
        required List<int> syncKey,
        required String baseUrl,
        required String vaultId}) =>
    RustLib.instance.api.crateApiWebSyncSyncManagedVaultPrepareWebPushBatch(
        appDir: appDir,
        key: key,
        syncKey: syncKey,
        baseUrl: baseUrl,
        vaultId: vaultId);

Future<String> syncManagedVaultApplyWebPushResponse(
        {required String appDir,
        required String baseUrl,
        required String vaultId,
        required String batchJson,
        required String responseJson}) =>
    RustLib.instance.api.crateApiWebSyncSyncManagedVaultApplyWebPushResponse(
        appDir: appDir,
        baseUrl: baseUrl,
        vaultId: vaultId,
        batchJson: batchJson,
        responseJson: responseJson);

Future<String> syncManagedVaultPrepareWebPushMediaUpload(
        {required String appDir,
        required List<int> key,
        required List<int> syncKey,
        required String baseUrl,
        required String vaultId,
        required String actionJson,
        required String mediaPhase}) =>
    RustLib.instance.api
        .crateApiWebSyncSyncManagedVaultPrepareWebPushMediaUpload(
            appDir: appDir,
            key: key,
            syncKey: syncKey,
            baseUrl: baseUrl,
            vaultId: vaultId,
            actionJson: actionJson,
            mediaPhase: mediaPhase);

Future<bool> syncManagedVaultRecordWebPushMediaResult(
        {required String appDir,
        required String baseUrl,
        required String vaultId,
        required String actionJson,
        required bool success,
        String? errorMessage}) =>
    RustLib.instance.api
        .crateApiWebSyncSyncManagedVaultRecordWebPushMediaResult(
            appDir: appDir,
            baseUrl: baseUrl,
            vaultId: vaultId,
            actionJson: actionJson,
            success: success,
            errorMessage: errorMessage);

Future<bool> syncManagedVaultCompleteWebPushMediaBatch(
        {required String appDir,
        required List<int> key,
        required String baseUrl,
        required String vaultId,
        required String batchJson}) =>
    RustLib.instance.api
        .crateApiWebSyncSyncManagedVaultCompleteWebPushMediaBatch(
            appDir: appDir,
            key: key,
            baseUrl: baseUrl,
            vaultId: vaultId,
            batchJson: batchJson);
