// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key_from_bytes`

String syncManagedVaultReadWebPullState(
        {required String appDir,
        required String baseUrl,
        required String vaultId}) =>
    RustLib.instance.api.crateApiWebSyncSyncManagedVaultReadWebPullState(
        appDir: appDir, baseUrl: baseUrl, vaultId: vaultId);

String syncManagedVaultApplyWebPullPage(
        {required String appDir,
        required List<int> key,
        required List<int> syncKey,
        required String baseUrl,
        required String vaultId,
        required String responseJson}) =>
    RustLib.instance.api.crateApiWebSyncSyncManagedVaultApplyWebPullPage(
        appDir: appDir,
        key: key,
        syncKey: syncKey,
        baseUrl: baseUrl,
        vaultId: vaultId,
        responseJson: responseJson);
