// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class KnowledgePageChangeRecord {
  final String changeId;
  final String pageId;
  final KnowledgePageChangeType changeType;
  final String actor;
  final String? reason;
  final bool answerImpacted;
  final PlatformInt64 createdAtMs;

  const KnowledgePageChangeRecord({
    required this.changeId,
    required this.pageId,
    required this.changeType,
    required this.actor,
    this.reason,
    required this.answerImpacted,
    required this.createdAtMs,
  });

  @override
  int get hashCode =>
      changeId.hashCode ^
      pageId.hashCode ^
      changeType.hashCode ^
      actor.hashCode ^
      reason.hashCode ^
      answerImpacted.hashCode ^
      createdAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgePageChangeRecord &&
          runtimeType == other.runtimeType &&
          changeId == other.changeId &&
          pageId == other.pageId &&
          changeType == other.changeType &&
          actor == other.actor &&
          reason == other.reason &&
          answerImpacted == other.answerImpacted &&
          createdAtMs == other.createdAtMs;
}

enum KnowledgePageChangeType {
  created,
  updated,
  corrected,
  downgraded,
  muted,
  archived,
  removed,
  merged,
  ;
}
