// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum KnowledgeLintKind {
  conflict,
  staleness,
  fragmentation,
  unusedKnowledge,
  evidenceWeakness,
  regenerationRisk,
  ;
}

class KnowledgeLintRecord {
  final String lintId;
  final String pageId;
  final KnowledgeLintKind kind;
  final String summary;
  final PlatformInt64 createdAtMs;

  const KnowledgeLintRecord({
    required this.lintId,
    required this.pageId,
    required this.kind,
    required this.summary,
    required this.createdAtMs,
  });

  @override
  int get hashCode =>
      lintId.hashCode ^
      pageId.hashCode ^
      kind.hashCode ^
      summary.hashCode ^
      createdAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeLintRecord &&
          runtimeType == other.runtimeType &&
          lintId == other.lintId &&
          pageId == other.pageId &&
          kind == other.kind &&
          summary == other.summary &&
          createdAtMs == other.createdAtMs;
}
