// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ContentKnowledgeDocument {
  final String documentId;
  final KnowledgeOriginType originType;
  final KnowledgeSourceKind sourceKind;
  final KnowledgeRole role;
  final String? language;
  final double qualityScore;
  final PlatformInt64 createdAtMs;
  final PlatformInt64 updatedAtMs;
  final KnowledgeVersionSet versions;
  final KnowledgeAnchorSet anchors;
  final String? title;
  final String? summary;
  final String rawText;
  final String normalizedText;

  const ContentKnowledgeDocument({
    required this.documentId,
    required this.originType,
    required this.sourceKind,
    required this.role,
    this.language,
    required this.qualityScore,
    required this.createdAtMs,
    required this.updatedAtMs,
    required this.versions,
    required this.anchors,
    this.title,
    this.summary,
    required this.rawText,
    required this.normalizedText,
  });

  @override
  int get hashCode =>
      documentId.hashCode ^
      originType.hashCode ^
      sourceKind.hashCode ^
      role.hashCode ^
      language.hashCode ^
      qualityScore.hashCode ^
      createdAtMs.hashCode ^
      updatedAtMs.hashCode ^
      versions.hashCode ^
      anchors.hashCode ^
      title.hashCode ^
      summary.hashCode ^
      rawText.hashCode ^
      normalizedText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContentKnowledgeDocument &&
          runtimeType == other.runtimeType &&
          documentId == other.documentId &&
          originType == other.originType &&
          sourceKind == other.sourceKind &&
          role == other.role &&
          language == other.language &&
          qualityScore == other.qualityScore &&
          createdAtMs == other.createdAtMs &&
          updatedAtMs == other.updatedAtMs &&
          versions == other.versions &&
          anchors == other.anchors &&
          title == other.title &&
          summary == other.summary &&
          rawText == other.rawText &&
          normalizedText == other.normalizedText;
}

class KnowledgeAnchorSet {
  final String? messageId;
  final String? conversationId;
  final String? attachmentSha256;
  final PlatformInt64? pageIndex;
  final PlatformInt64? frameIndex;
  final PlatformInt64? startMs;
  final PlatformInt64? endMs;
  final String? speaker;
  final String? sectionLabel;
  final String? sourceFilename;

  const KnowledgeAnchorSet({
    this.messageId,
    this.conversationId,
    this.attachmentSha256,
    this.pageIndex,
    this.frameIndex,
    this.startMs,
    this.endMs,
    this.speaker,
    this.sectionLabel,
    this.sourceFilename,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      conversationId.hashCode ^
      attachmentSha256.hashCode ^
      pageIndex.hashCode ^
      frameIndex.hashCode ^
      startMs.hashCode ^
      endMs.hashCode ^
      speaker.hashCode ^
      sectionLabel.hashCode ^
      sourceFilename.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeAnchorSet &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          conversationId == other.conversationId &&
          attachmentSha256 == other.attachmentSha256 &&
          pageIndex == other.pageIndex &&
          frameIndex == other.frameIndex &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          speaker == other.speaker &&
          sectionLabel == other.sectionLabel &&
          sourceFilename == other.sourceFilename;
}

class KnowledgeIndexStatus {
  final String status;
  final bool rebuildRequired;
  final String? staleReason;
  final String? lastError;
  final PlatformInt64? lastRebuildStartedAtMs;
  final PlatformInt64? lastRebuildCompletedAtMs;
  final String? currentDocumentId;
  final String? currentStage;
  final PlatformInt64 documentsIndexed;
  final PlatformInt64 unitsIndexed;
  final PlatformInt64 embeddingsIndexed;
  final PlatformInt64 totalDocuments;
  final String? lastIndexedModelName;
  final PlatformInt64? lastIndexedDim;
  final KnowledgeVersionSet versions;

  const KnowledgeIndexStatus({
    required this.status,
    required this.rebuildRequired,
    this.staleReason,
    this.lastError,
    this.lastRebuildStartedAtMs,
    this.lastRebuildCompletedAtMs,
    this.currentDocumentId,
    this.currentStage,
    required this.documentsIndexed,
    required this.unitsIndexed,
    required this.embeddingsIndexed,
    required this.totalDocuments,
    this.lastIndexedModelName,
    this.lastIndexedDim,
    required this.versions,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      rebuildRequired.hashCode ^
      staleReason.hashCode ^
      lastError.hashCode ^
      lastRebuildStartedAtMs.hashCode ^
      lastRebuildCompletedAtMs.hashCode ^
      currentDocumentId.hashCode ^
      currentStage.hashCode ^
      documentsIndexed.hashCode ^
      unitsIndexed.hashCode ^
      embeddingsIndexed.hashCode ^
      totalDocuments.hashCode ^
      lastIndexedModelName.hashCode ^
      lastIndexedDim.hashCode ^
      versions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeIndexStatus &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          rebuildRequired == other.rebuildRequired &&
          staleReason == other.staleReason &&
          lastError == other.lastError &&
          lastRebuildStartedAtMs == other.lastRebuildStartedAtMs &&
          lastRebuildCompletedAtMs == other.lastRebuildCompletedAtMs &&
          currentDocumentId == other.currentDocumentId &&
          currentStage == other.currentStage &&
          documentsIndexed == other.documentsIndexed &&
          unitsIndexed == other.unitsIndexed &&
          embeddingsIndexed == other.embeddingsIndexed &&
          totalDocuments == other.totalDocuments &&
          lastIndexedModelName == other.lastIndexedModelName &&
          lastIndexedDim == other.lastIndexedDim &&
          versions == other.versions;
}

enum KnowledgeOriginType {
  message,
  attachment,
  importedExternal,
  generated,
  ;
}

enum KnowledgeRetrievalLayer {
  document,
  section,
  chunk,
  ;
}

enum KnowledgeRole {
  title,
  summary,
  body,
  metadata,
  caption,
  evidence,
  ;
}

class KnowledgeSearchResult {
  final String documentId;
  final String? unitId;
  final KnowledgeUnitKind? unitKind;
  final KnowledgeRetrievalLayer layer;
  final KnowledgeSourceKind sourceKind;
  final KnowledgeRole role;
  final String? title;
  final String? summary;
  final String snippet;
  final double score;
  final double semanticScore;
  final double lexicalScore;
  final KnowledgeAnchorSet anchors;
  final PlatformInt64 createdAtMs;
  final PlatformInt64 updatedAtMs;

  const KnowledgeSearchResult({
    required this.documentId,
    this.unitId,
    this.unitKind,
    required this.layer,
    required this.sourceKind,
    required this.role,
    this.title,
    this.summary,
    required this.snippet,
    required this.score,
    required this.semanticScore,
    required this.lexicalScore,
    required this.anchors,
    required this.createdAtMs,
    required this.updatedAtMs,
  });

  @override
  int get hashCode =>
      documentId.hashCode ^
      unitId.hashCode ^
      unitKind.hashCode ^
      layer.hashCode ^
      sourceKind.hashCode ^
      role.hashCode ^
      title.hashCode ^
      summary.hashCode ^
      snippet.hashCode ^
      score.hashCode ^
      semanticScore.hashCode ^
      lexicalScore.hashCode ^
      anchors.hashCode ^
      createdAtMs.hashCode ^
      updatedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeSearchResult &&
          runtimeType == other.runtimeType &&
          documentId == other.documentId &&
          unitId == other.unitId &&
          unitKind == other.unitKind &&
          layer == other.layer &&
          sourceKind == other.sourceKind &&
          role == other.role &&
          title == other.title &&
          summary == other.summary &&
          snippet == other.snippet &&
          score == other.score &&
          semanticScore == other.semanticScore &&
          lexicalScore == other.lexicalScore &&
          anchors == other.anchors &&
          createdAtMs == other.createdAtMs &&
          updatedAtMs == other.updatedAtMs;
}

enum KnowledgeSourceKind {
  rawText,
  extractedText,
  readableText,
  ocrText,
  transcript,
  imageUnderstanding,
  videoKeyframeUnderstanding,
  metadata,
  summary,
  ;
}

class KnowledgeUnit {
  final String unitId;
  final String documentId;
  final String? parentUnitId;
  final KnowledgeUnitKind unitKind;
  final KnowledgeSourceKind sourceKind;
  final KnowledgeRole role;
  final PlatformInt64 ordinal;
  final PlatformInt64 tokenCount;
  final String rawText;
  final String normalizedText;
  final KnowledgeAnchorSet anchors;
  final String? prevUnitId;
  final String? nextUnitId;
  final PlatformInt64 createdAtMs;
  final PlatformInt64 updatedAtMs;

  const KnowledgeUnit({
    required this.unitId,
    required this.documentId,
    this.parentUnitId,
    required this.unitKind,
    required this.sourceKind,
    required this.role,
    required this.ordinal,
    required this.tokenCount,
    required this.rawText,
    required this.normalizedText,
    required this.anchors,
    this.prevUnitId,
    this.nextUnitId,
    required this.createdAtMs,
    required this.updatedAtMs,
  });

  @override
  int get hashCode =>
      unitId.hashCode ^
      documentId.hashCode ^
      parentUnitId.hashCode ^
      unitKind.hashCode ^
      sourceKind.hashCode ^
      role.hashCode ^
      ordinal.hashCode ^
      tokenCount.hashCode ^
      rawText.hashCode ^
      normalizedText.hashCode ^
      anchors.hashCode ^
      prevUnitId.hashCode ^
      nextUnitId.hashCode ^
      createdAtMs.hashCode ^
      updatedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeUnit &&
          runtimeType == other.runtimeType &&
          unitId == other.unitId &&
          documentId == other.documentId &&
          parentUnitId == other.parentUnitId &&
          unitKind == other.unitKind &&
          sourceKind == other.sourceKind &&
          role == other.role &&
          ordinal == other.ordinal &&
          tokenCount == other.tokenCount &&
          rawText == other.rawText &&
          normalizedText == other.normalizedText &&
          anchors == other.anchors &&
          prevUnitId == other.prevUnitId &&
          nextUnitId == other.nextUnitId &&
          createdAtMs == other.createdAtMs &&
          updatedAtMs == other.updatedAtMs;
}

enum KnowledgeUnitKind {
  section,
  segment,
  chunk,
  ;
}

class KnowledgeVersionSet {
  final PlatformInt64 schemaVersion;
  final PlatformInt64 normalizationVersion;
  final PlatformInt64 segmentationVersion;
  final PlatformInt64 embeddingPolicyVersion;
  final PlatformInt64 retrievalPolicyVersion;

  const KnowledgeVersionSet({
    required this.schemaVersion,
    required this.normalizationVersion,
    required this.segmentationVersion,
    required this.embeddingPolicyVersion,
    required this.retrievalPolicyVersion,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      normalizationVersion.hashCode ^
      segmentationVersion.hashCode ^
      embeddingPolicyVersion.hashCode ^
      retrievalPolicyVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeVersionSet &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          normalizationVersion == other.normalizationVersion &&
          segmentationVersion == other.segmentationVersion &&
          embeddingPolicyVersion == other.embeddingPolicyVersion &&
          retrievalPolicyVersion == other.retrievalPolicyVersion;
}

class KnowledgeViewerDocument {
  final ContentKnowledgeDocument document;
  final PlatformInt64 totalUnits;
  final PlatformInt64 sectionCount;
  final PlatformInt64 chunkCount;

  const KnowledgeViewerDocument({
    required this.document,
    required this.totalUnits,
    required this.sectionCount,
    required this.chunkCount,
  });

  @override
  int get hashCode =>
      document.hashCode ^
      totalUnits.hashCode ^
      sectionCount.hashCode ^
      chunkCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeViewerDocument &&
          runtimeType == other.runtimeType &&
          document == other.document &&
          totalUnits == other.totalUnits &&
          sectionCount == other.sectionCount &&
          chunkCount == other.chunkCount;
}

class KnowledgeViewerPage {
  final String documentId;
  final KnowledgeUnitKind? unitKind;
  final PlatformInt64 offset;
  final PlatformInt64 limit;
  final PlatformInt64 total;
  final List<KnowledgeUnit> units;

  const KnowledgeViewerPage({
    required this.documentId,
    this.unitKind,
    required this.offset,
    required this.limit,
    required this.total,
    required this.units,
  });

  @override
  int get hashCode =>
      documentId.hashCode ^
      unitKind.hashCode ^
      offset.hashCode ^
      limit.hashCode ^
      total.hashCode ^
      units.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeViewerPage &&
          runtimeType == other.runtimeType &&
          documentId == other.documentId &&
          unitKind == other.unitKind &&
          offset == other.offset &&
          limit == other.limit &&
          total == other.total &&
          units == other.units;
}
