// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'history.dart';
import 'lint.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class KnowledgeAnswerPolicy {
  final bool defaultAllowed;
  final bool requiresTemporalFraming;

  const KnowledgeAnswerPolicy({
    required this.defaultAllowed,
    required this.requiresTemporalFraming,
  });

  @override
  int get hashCode =>
      defaultAllowed.hashCode ^ requiresTemporalFraming.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeAnswerPolicy &&
          runtimeType == other.runtimeType &&
          defaultAllowed == other.defaultAllowed &&
          requiresTemporalFraming == other.requiresTemporalFraming;
}

class KnowledgePage {
  final String pageId;
  final KnowledgePageType pageType;
  final String title;
  final String currentSummary;
  final String currentBody;
  final KnowledgePageState state;
  final KnowledgeAnswerPolicy answerPolicy;
  final double confidenceLevel;
  final PlatformInt64 createdAtMs;
  final PlatformInt64 updatedAtMs;
  final PlatformInt64? lastUsedAtMs;
  final PlatformInt64 sourceCount;
  final PlatformInt64 conflictCount;
  final bool humanCorrected;
  final List<String> tags;
  final List<String> primaryEvidenceIds;
  final List<String> relatedPageIds;

  const KnowledgePage({
    required this.pageId,
    required this.pageType,
    required this.title,
    required this.currentSummary,
    required this.currentBody,
    required this.state,
    required this.answerPolicy,
    required this.confidenceLevel,
    required this.createdAtMs,
    required this.updatedAtMs,
    this.lastUsedAtMs,
    required this.sourceCount,
    required this.conflictCount,
    required this.humanCorrected,
    required this.tags,
    required this.primaryEvidenceIds,
    required this.relatedPageIds,
  });

  @override
  int get hashCode =>
      pageId.hashCode ^
      pageType.hashCode ^
      title.hashCode ^
      currentSummary.hashCode ^
      currentBody.hashCode ^
      state.hashCode ^
      answerPolicy.hashCode ^
      confidenceLevel.hashCode ^
      createdAtMs.hashCode ^
      updatedAtMs.hashCode ^
      lastUsedAtMs.hashCode ^
      sourceCount.hashCode ^
      conflictCount.hashCode ^
      humanCorrected.hashCode ^
      tags.hashCode ^
      primaryEvidenceIds.hashCode ^
      relatedPageIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgePage &&
          runtimeType == other.runtimeType &&
          pageId == other.pageId &&
          pageType == other.pageType &&
          title == other.title &&
          currentSummary == other.currentSummary &&
          currentBody == other.currentBody &&
          state == other.state &&
          answerPolicy == other.answerPolicy &&
          confidenceLevel == other.confidenceLevel &&
          createdAtMs == other.createdAtMs &&
          updatedAtMs == other.updatedAtMs &&
          lastUsedAtMs == other.lastUsedAtMs &&
          sourceCount == other.sourceCount &&
          conflictCount == other.conflictCount &&
          humanCorrected == other.humanCorrected &&
          tags == other.tags &&
          primaryEvidenceIds == other.primaryEvidenceIds &&
          relatedPageIds == other.relatedPageIds;
}

class KnowledgePageDetail {
  final KnowledgePage page;
  final List<String> sourceDocumentIds;
  final List<String> claimIds;
  final List<KnowledgePageChangeRecord> history;
  final List<KnowledgePageVersionSnapshot> versionSnapshots;
  final List<KnowledgePageEvidenceEntry> evidenceEntries;
  final List<KnowledgeLintRecord> lintRecords;

  const KnowledgePageDetail({
    required this.page,
    required this.sourceDocumentIds,
    required this.claimIds,
    required this.history,
    required this.versionSnapshots,
    required this.evidenceEntries,
    required this.lintRecords,
  });

  @override
  int get hashCode =>
      page.hashCode ^
      sourceDocumentIds.hashCode ^
      claimIds.hashCode ^
      history.hashCode ^
      versionSnapshots.hashCode ^
      evidenceEntries.hashCode ^
      lintRecords.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgePageDetail &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          sourceDocumentIds == other.sourceDocumentIds &&
          claimIds == other.claimIds &&
          history == other.history &&
          versionSnapshots == other.versionSnapshots &&
          evidenceEntries == other.evidenceEntries &&
          lintRecords == other.lintRecords;
}

class KnowledgePageEvidenceEntry {
  final String evidenceId;
  final KnowledgePageEvidenceKind kind;
  final String summary;
  final List<String> sourceRefIds;
  final PlatformInt64 createdAtMs;

  const KnowledgePageEvidenceEntry({
    required this.evidenceId,
    required this.kind,
    required this.summary,
    required this.sourceRefIds,
    required this.createdAtMs,
  });

  @override
  int get hashCode =>
      evidenceId.hashCode ^
      kind.hashCode ^
      summary.hashCode ^
      sourceRefIds.hashCode ^
      createdAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgePageEvidenceEntry &&
          runtimeType == other.runtimeType &&
          evidenceId == other.evidenceId &&
          kind == other.kind &&
          summary == other.summary &&
          sourceRefIds == other.sourceRefIds &&
          createdAtMs == other.createdAtMs;
}

enum KnowledgePageEvidenceKind {
  support,
  conflict,
  supplement,
  ;
}

enum KnowledgePageState {
  active,
  needsReview,
  outdated,
  answerMuted,
  archived,
  removed,
  ;
}

class KnowledgePageSummary {
  final String pageId;
  final KnowledgePageType pageType;
  final String title;
  final String currentSummary;
  final KnowledgePageState state;
  final KnowledgeAnswerPolicy answerPolicy;
  final PlatformInt64 updatedAtMs;
  final PlatformInt64? lastUsedAtMs;
  final PlatformInt64 sourceCount;
  final PlatformInt64 conflictCount;
  final bool humanCorrected;
  final List<String> tags;
  final List<String> primaryEvidenceIds;

  const KnowledgePageSummary({
    required this.pageId,
    required this.pageType,
    required this.title,
    required this.currentSummary,
    required this.state,
    required this.answerPolicy,
    required this.updatedAtMs,
    this.lastUsedAtMs,
    required this.sourceCount,
    required this.conflictCount,
    required this.humanCorrected,
    required this.tags,
    required this.primaryEvidenceIds,
  });

  @override
  int get hashCode =>
      pageId.hashCode ^
      pageType.hashCode ^
      title.hashCode ^
      currentSummary.hashCode ^
      state.hashCode ^
      answerPolicy.hashCode ^
      updatedAtMs.hashCode ^
      lastUsedAtMs.hashCode ^
      sourceCount.hashCode ^
      conflictCount.hashCode ^
      humanCorrected.hashCode ^
      tags.hashCode ^
      primaryEvidenceIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgePageSummary &&
          runtimeType == other.runtimeType &&
          pageId == other.pageId &&
          pageType == other.pageType &&
          title == other.title &&
          currentSummary == other.currentSummary &&
          state == other.state &&
          answerPolicy == other.answerPolicy &&
          updatedAtMs == other.updatedAtMs &&
          lastUsedAtMs == other.lastUsedAtMs &&
          sourceCount == other.sourceCount &&
          conflictCount == other.conflictCount &&
          humanCorrected == other.humanCorrected &&
          tags == other.tags &&
          primaryEvidenceIds == other.primaryEvidenceIds;
}

enum KnowledgePageType {
  aboutMe,
  preferences,
  currentFocus,
  activeThreads,
  recentEvents,
  people,
  topics,
  openQuestions,
  ;
}

class KnowledgePageVersionSnapshot {
  final String versionId;
  final String pageId;
  final String title;
  final String summary;
  final String body;
  final KnowledgePageState state;
  final KnowledgeAnswerPolicy answerPolicy;
  final double confidenceLevel;
  final PlatformInt64 sourceCount;
  final PlatformInt64 conflictCount;
  final bool humanCorrected;
  final String actor;
  final KnowledgePageChangeType changeType;
  final String? reason;
  final PlatformInt64 createdAtMs;

  const KnowledgePageVersionSnapshot({
    required this.versionId,
    required this.pageId,
    required this.title,
    required this.summary,
    required this.body,
    required this.state,
    required this.answerPolicy,
    required this.confidenceLevel,
    required this.sourceCount,
    required this.conflictCount,
    required this.humanCorrected,
    required this.actor,
    required this.changeType,
    this.reason,
    required this.createdAtMs,
  });

  @override
  int get hashCode =>
      versionId.hashCode ^
      pageId.hashCode ^
      title.hashCode ^
      summary.hashCode ^
      body.hashCode ^
      state.hashCode ^
      answerPolicy.hashCode ^
      confidenceLevel.hashCode ^
      sourceCount.hashCode ^
      conflictCount.hashCode ^
      humanCorrected.hashCode ^
      actor.hashCode ^
      changeType.hashCode ^
      reason.hashCode ^
      createdAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgePageVersionSnapshot &&
          runtimeType == other.runtimeType &&
          versionId == other.versionId &&
          pageId == other.pageId &&
          title == other.title &&
          summary == other.summary &&
          body == other.body &&
          state == other.state &&
          answerPolicy == other.answerPolicy &&
          confidenceLevel == other.confidenceLevel &&
          sourceCount == other.sourceCount &&
          conflictCount == other.conflictCount &&
          humanCorrected == other.humanCorrected &&
          actor == other.actor &&
          changeType == other.changeType &&
          reason == other.reason &&
          createdAtMs == other.createdAtMs;
}

enum KnowledgeWrongReason {
  statementWrong,
  outdated,
  incomplete,
  shouldNotRemember,
  ;
}
